# https://hackmd.io/@gNH0A9jtQC6WsVrY4tI2Jg/rJP29VDNw
# adjustMode: 
#   0: toggle
#   1: slider
#
# type: 
#   0: 17
#   1: third party

platform:
  ios:
    default:
      enable: true
      features:
        - id: 17skin
          enable: true
          min: 0
          max: 1
          default: 0
          adjustMode: 0
          displayName: streamer_beautify_homemade
          iconUrl: https://assets-17app.akamaized.net/7038316c-9c8c-4df7-b71a-488a713235d2.png
          type: 0
        - id: skinSoften #磨皮
          enable: true
          min: 0
          max: 100
          default: 55
          adjustMode: 1
          displayName: streamer_beautify_scrub
          iconUrl: https://assets-17app.akamaized.net/c58a63c4-7f80-4042-a948-76b23bee0ed3.png
          type: 1
        - id: skinWhitening #白皙
          enable: true
          min: 0
          max: 1
          default: 0.55
          adjustMode: 1
          displayName: streamer_beautify_whitening
          iconUrl: https://assets-17app.akamaized.net/55fe437f-a129-4211-ae41-6407a85e2624.png
          type: 1
        - id: skinRedden
          enable: true
          min: 0
          max: 1
          default: 0.55
          adjustMode: 1
          displayName: streamer_beautify_rosy
          iconUrl: https://assets-17app.akamaized.net/3022e1b2-6cbf-4d09-a5db-49f1068fa254.png
          type: 1
        - id: bigEye
          enable: true
          min: 0
          max: 50
          default: 5
          adjustMode: 1
          displayName: streamer_beautify_bigeyes
          iconUrl: https://assets-17app.akamaized.net/0b412bdd-61fd-4aaf-bc54-07465d813d5c.png
          type: 1
        - id: thinFace
          enable: true
          min: 0
          max: 50
          default: 5
          adjustMode: 1
          displayName: streamer_beautify_slimface
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: shrinkJaw # 小臉
          enable: true
          min: 0
          max: 1
          default: 0.1
          adjustMode: 1
          displayName: shrinkJaw
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: contrast # 對比度
          enable: true
          min: 0
          max: 1
          default: 0.2
          adjustMode: 1
          displayName: contrast
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: saturation # 飽和度
          enable: true
          min: 0
          max: 1
          default: 0.3
          adjustMode: 1
          displayName: saturation
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: narrowFace # 窄臉
          enable: true
          min: 0
          max: 1
          default: 0.5
          adjustMode: 1
          displayName: narrowFace
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: roundEyes # 圓眼
          enable: true
          min: 0
          max: 1
          default: 0.5
          adjustMode: 1
          displayName: roundEyes
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: sharpen # 銳化
          enable: true
          min: 0
          max: 1
          default: 0.5
          adjustMode: 1
          displayName: sharpen
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
#    iPhone5,3:
  android:
    default:
      enable: true
      features:
        - id: 17skin
          enable: true
          min: 0
          max: 1
          default: 0
          adjustMode: 0
          displayName: streamer_beautify_homemade
          iconUrl: https://assets-17app.akamaized.net/7038316c-9c8c-4df7-b71a-488a713235d2.png
          type: 0
        - id: skinSoften #磨皮
          enable: true
          min: 0
          max: 100
          default: 55
          adjustMode: 1
          displayName: streamer_beautify_scrub
          iconUrl: https://assets-17app.akamaized.net/c58a63c4-7f80-4042-a948-76b23bee0ed3.png
          type: 1
        - id: skinWhitening #白皙
          enable: true
          min: 0
          max: 1
          default: 0.55
          adjustMode: 1
          displayName: streamer_beautify_whitening
          iconUrl: https://assets-17app.akamaized.net/55fe437f-a129-4211-ae41-6407a85e2624.png
          type: 1
        - id: skinRedden
          enable: true
          min: 0
          max: 1
          default: 0.55
          adjustMode: 1
          displayName: streamer_beautify_rosy
          iconUrl: https://assets-17app.akamaized.net/3022e1b2-6cbf-4d09-a5db-49f1068fa254.png
          type: 1
        - id: bigEye
          enable: true
          min: 0
          max: 50
          default: 5
          adjustMode: 1
          displayName: streamer_beautify_bigeyes
          iconUrl: https://assets-17app.akamaized.net/0b412bdd-61fd-4aaf-bc54-07465d813d5c.png
          type: 1
        - id: thinFace
          enable: true
          min: 0
          max: 50
          default: 5
          adjustMode: 1
          displayName: streamer_beautify_slimface
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: shrinkJaw # 小臉
          enable: true
          min: 0
          max: 1
          default: 0.1
          adjustMode: 1
          displayName: shrinkJaw
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: contrast # 對比度
          enable: true
          min: 0
          max: 1
          default: 0.2
          adjustMode: 1
          displayName: contrast
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: saturation # 飽和度
          enable: true
          min: 0
          max: 1
          default: 0.3
          adjustMode: 1
          displayName: saturation
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: narrowFace # 窄臉
          enable: true
          min: 0
          max: 1
          default: 0.5
          adjustMode: 1
          displayName: narrowFace
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: roundEyes # 圓眼
          enable: true
          min: 0
          max: 1
          default: 0.5
          adjustMode: 1
          displayName: roundEyes
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: sharpen # 銳化
          enable: true
          min: 0
          max: 1
          default: 0.5
          adjustMode: 1
          displayName: sharpen
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
#    Pixel 2: