# https://hackmd.io/@gNH0A9jtQC6WsVrY4tI2Jg/rJP29VDNw
# adjustMode: 
#   0: toggle
#   1: slider
#
# type: 
#   0: 17
#   1: third party

platform:
  ios:
    default:
      enable: false
      features:
        - id: skinRedden
          enable: true
          min: 0
          max: 1
          default: 0.4
          adjustMode: 1
          displayName: streamer_beautify_rosy
          iconUrl: http://cdn.17app.co/producer-badge-razor-38x38px.png
          type: 1
        - id: skinWhitening
          enable: true
          min: 0
          max: 1
          default: 0.6
          adjustMode: 1
          displayName: streamer_beautify_whitening
          iconUrl: http://cdn.17app.co/producer-badge-tower-38x38px.png
          type: 1
        - id: skinSoften
          enable: true
          min: 5
          max: 95
          default: 45
          adjustMode: 1
          displayName: streamer_beautify_scrub
          iconUrl: http://cdn.17app.co/producer-badge-alex-38x38px.png
          type: 1
        - id: 17skin
          enable: true
          min: 0
          max: 1
          default: 0
          adjustMode: 0
          displayName: streamer_beautify_homemade
          iconUrl: http://cdn.17app.co/producer-badge-jerryc-38x38px.png
          type: 0
        - id: bigEye
          enable: true
          min: 0
          max: 100
          default: 50
          adjustMode: 1
          displayName: streamer_beautify_bigeyes
          iconUrl: http://cdn.17app.co/producer-badge-starrchen-38x38px.png
          type: 1
        - id: thinFace
          enable: true
          min: 1
          max: 99
          default: 49
          adjustMode: 1
          displayName: streamer_beautify_slimface
          iconUrl: http://cdn.17app.co/producer-badge-roger-38x38px.png
          type: 1
        - id: shrinkJaw # 小臉
          enable: true
          min: 0
          max: 1
          default: 0.1
          adjustMode: 1
          displayName: shrinkJaw
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: contrast # 對比度
          enable: true
          min: 0
          max: 1
          default: 0.2
          adjustMode: 1
          displayName: contrast
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: saturation # 飽和度
          enable: true
          min: 0
          max: 1
          default: 0.3
          adjustMode: 1
          displayName: saturation
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: narrowFace # 窄臉
          enable: true
          min: 0
          max: 1
          default: 0.5
          adjustMode: 1
          displayName: narrowFace
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: roundEyes # 圓眼
          enable: true
          min: 0
          max: 1
          default: 0.5
          adjustMode: 1
          displayName: roundEyes
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: sharpen # 銳化
          enable: true
          min: 0
          max: 1
          default: 0.5
          adjustMode: 1
          displayName: sharpen
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
    iPhone5,3:
  android:
    default:
      enable: false
      features:
        - id: skinRedden
          enable: true
          min: 0
          max: 1
          default: 0.4
          adjustMode: 1
          displayName: streamer_beautify_rosy
          iconUrl: http://cdn.17app.co/producer-badge-razor-38x38px.png
          type: 1
        - id: skinWhitening
          enable: true
          min: 0
          max: 1
          default: 0.6
          adjustMode: 1
          displayName: streamer_beautify_whitening
          iconUrl: http://cdn.17app.co/producer-badge-tower-38x38px.png
          type: 1
        - id: skinSoften
          enable: true
          min: 5
          max: 95
          default: 45
          adjustMode: 1
          displayName: streamer_beautify_scrub
          iconUrl: http://cdn.17app.co/producer-badge-alex-38x38px.png
          type: 1
        - id: 17skin
          enable: true
          min: 0
          max: 1
          default: 0
          adjustMode: 0
          displayName: streamer_beautify_homemade
          iconUrl: http://cdn.17app.co/producer-badge-jerryc-38x38px.png
          type: 0
        - id: bigEye
          enable: true
          min: 0
          max: 100
          default: 50
          adjustMode: 1
          displayName: streamer_beautify_bigeyes
          iconUrl: http://cdn.17app.co/producer-badge-starrchen-38x38px.png
          type: 1
        - id: thinFace
          enable: true
          min: 1
          max: 99
          default: 49
          adjustMode: 1
          displayName: streamer_beautify_slimface
          iconUrl: http://cdn.17app.co/producer-badge-roger-38x38px.png
          type: 1
        - id: shrinkJaw # 小臉
          enable: true
          min: 0
          max: 1
          default: 0.1
          adjustMode: 1
          displayName: shrinkJaw
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: contrast # 對比度
          enable: true
          min: 0
          max: 1
          default: 0.2
          adjustMode: 1
          displayName: contrast
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: saturation # 飽和度
          enable: true
          min: 0
          max: 1
          default: 0.3
          adjustMode: 1
          displayName: saturation
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: narrowFace # 窄臉
          enable: true
          min: 0
          max: 1
          default: 0.5
          adjustMode: 1
          displayName: narrowFace
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: roundEyes # 圓眼
          enable: true
          min: 0
          max: 1
          default: 0.5
          adjustMode: 1
          displayName: roundEyes
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
        - id: sharpen # 銳化
          enable: true
          min: 0
          max: 1
          default: 0.5
          adjustMode: 1
          displayName: sharpen
          iconUrl: https://assets-17app.akamaized.net/cb046032-672d-4b5d-9227-307c258da9ec.png
          type: 1
    # Pixel 2:
