
eventBasedIAP:

productBasedIAP:

secretIAP:

defaultIAP:
  layoutInfo:
    highlightBgURL: "https://cdn.17app.co/b505d3b8-994d-42cd-a86f-304ac491040c.png"
    highlightIconURL: "https://assets-17app.akamaized.net/eeae83cf-ae8b-48a8-b465-a5180f87b8f9.png"
  colorInfo:
    pointColor: "#28232D"
    bonusPointColor: "#F5487D"
    priceColor: "#28232D"
  pointProducts:
    - productID: "baas_media17_points_35980"
      bonusPoint: 0
      shouldHighlight:  true
    - productID: "baas_media17_points_15420"
      bonusPoint: 0
      shouldHighlight:  false
    - productID: "baas_media17_points_8550"
      bonusPoint: 0
      shouldHighlight:  false
    - productID: "baas_media17_points_3540"
      bonusPoint: 0
      shouldHighlight:  false
    - productID: "baas_media17_points_1720"
      bonusPoint: 0
      shouldHighlight:  false
    - productID: "baas_media17_points_330"
      bonusPoint: 0
      shouldHighlight:  false
