watcher_channels:
  - "C466YU363" # eng-sre
  - "C13NQ5NKH" # eng-alert

payment_maintain:
  general_notify: "<@U02GTNQVBT4> @eng-web-billing"
  notify_rules: 
    - regex: "維護" 
      slack_ids: "@skyeye"

third_party:
  notify_rules: 
    - regex: "Redis Scheduled Maintenance" 
      slack_ids: "@oncall @sre"
    - regex: "Zendesk Maintenance"
      slack_ids: "@oncall @sre"
