watcher_channels:
  - "C466YU363" # eng-sre
  - "C13NQ5NKH" # eng-alert

payment_maintain:
  general_notice: "<@U02GTNQVBT4> @eng-web-billing"
  rules: 
    - regex: "維護" 
      notice_slack_ids: "@skyeye"
