# # example
#
# tag_streamer_recommendation_settings:
#   - id: chat
#     recommend_ids_for_male:
#       - 4ccb789d-4059-41cf-9505-b820579c2b48 # 范小姐
#       - ac021f94-9501-47eb-a7ba-1f626736ec96 # Sandyyyyyyyy
#     recommend_ids_for_female:
#       - cb46a35f-0ae6-487c-aad3-ea3ff5b8c838 # 微笑晴天
#       - 6443a434-4e3c-47c9-b59a-6f408a51e144 # 洛·克

tag_streamer_recommendation_settings:
  - id: chat
    recommend_ids_for_male:
    recommend_ids_for_female:

  - id: singing
    recommend_ids_for_male:
    recommend_ids_for_female:
