adjectives: []
enabled: true
  - 天馬行空的
  - 瘋狂的
  - 搞笑的
  - 嘻嘻哈哈的
  - 帥氣的
  - 生活多采多姿的
  - 快樂似神仙的
  - 口袋空空的
  - 想不到名字的
  - 腦袋空空的
  - 難過的
  - 沒有時間的
  - 無畏的
  - 快樂的
  - 有品味的
  - 美麗的
  - 可愛的
  - 華麗的
  - 進擊的
  - 閃閃發亮的
  - 友善的
  - 真誠的
  - 獨一無二的
  - 可愛又迷人的
  - 懶惰的
  - 無聊的
  - 淘氣的
  - 頑皮的
  - 慵懶的
  - 甜美的
  - 神秘的
  - 叛逆的
  - 高冷的
  - 愛遲到的
  - 傻氣的
  - 愛幻想的
  - 堅強的
  - 勇敢的
  - 無心的
  - 無知的
  - 一級棒的
  - 多重宇宙的
  - 聲音好聽的
  - 香噴噴的
  - 超浪漫的
  - 宅宅的
  - 文靜的
  - 厭世的
  - 法力無窮的
  - 事事順心的
  - 自由的
  - 嚴肅的
  - 寂寞的
  - 想賺大錢的
  - 愛吃肉的
  - 想交男友的
  - 想交女友的
  - 想午休的
  - 想下班的
  - 想上班的
  - 想翹班的
  - 想找工作的
  - 肚子餓的
  - 冷冰冰的
  - 放空的
  - 豪放不羈的
  - 玉樹臨風的
  - 沈默寡言的
  - 中樂透的
  - 狗屎運的
  - 刻在我心底的
  - 焦慮的
  - 重感情的
  - 苦澀的
  - 最偉大的
  - 最大尾的
  - 披星戴月的
  - 生氣的
  - 黏TT的
  - 酸溜溜的
  - 準備下班的
  - 炯炯有神的
  - 想自由的
  - 氣鼠人的
  - 昂首闊步的
  - 天長地久的
  - 浩瀚的
  - 精緻的
  - 活潑的
  - 發憤圖強的
  - 勤奮好學的
  - 傲嬌的
  - 任性的
  - 有料的
  - U質的
  - 暈船的
  - 多金的
  - 土豪的
  - 有錢的
  - 大方的
  - 大
  - 迷你
  - 小
  - 巨無霸
  - 傻憨的
  - 萌萌的
  - 煞氣a
  - 正直的
  - 粉嫩的
  - 年輕的
  - 孤獨的
  - 偏執的
  - 愛睡的
  - 酷酷的
  - 美翻的
  - 水水的
  - 超正的
  - 慢吞吞
  - 辣
  - 天才
  - 特別
  - 白色的
  - 長的
  - 甜
  - 高的
  - 猛的
  - 威的
  - 酷的
  - 派派的
  - 秋
  - 水的
  - 愛哭哭的
  - 當機的
  - 胡鬧的
  - 禮貌的
  - 嶄新的
  - 漂流的
  - 成熟的
  - 慢熟的
  - 失聯的
  - 溫暖的
  - 沉默的
  - 想妳的
  - 颯爽的
  - 緩慢的
  - 懷念的
  - 不失禮貌的
  - 冷漠的
  - 絕世
  - 屬於你的
  - 微笑的
  - 假笑的
  - 隨身的
  - 起肖的
  - 甜滋滋
  - 火辣辣
  - 燒燙燙
  - 蔚藍色的
  - 害羞的
  - 浪漫
  - 紛飛的
  - 奇妙
  - 魔幻
  - 親愛的
  - 強
  - 驚世駭俗
  - 狂
  - 絕無僅有
  - 世上唯一
  - 地表最美
  - 活躍
  - 高雄的
  - 台北的
  - 恰北北
  - 失禮的
  - 無條件的
  - 羞澀
  - 苦悶
  - 中暑的
  - 失戀的
  - 累累的
  - 愛吃的
  - 寶貝的
  - 不情願
  - 唯一的
  - 默默的
  - 認真
  - 可靠
  - 坦率
  - 聰明
  - 瀟灑
  - 內向
  - 英俊
  - 秘密的
  - 和煦的
  - 驕傲的
  - 徘徊的
  - 猶豫的
  - 濕眼眶的
  - 傷感的
  - 義無反顧的
  - 享受的
  - 期望的
  - 青春的
  - 霸氣的
  - 炫砲的
  - 你知道的
  - 平凡的
  - 輝煌的
  - 神秘的
  - 哭哭的
  - 燦爛的
  - 安靜的
  - 愛撒嬌的