endpoint: "http://34.121.90.130"
token: <SECRET_TAG>CiQAmBGjTWaxpMUuf5PWfvB8vzYyDnmxrblDBuN0WcJGuFoV0goSTAClekYIxILYBwU1VGjOmkDhAWXimWQ6Hlwth2FR/LmOla5WcgRM9g+b3cuLDwrqO98VUU4CXSYP8J/TOS6PTmKhBh6x3SAzrdcksz0=</SECRET_TAG>