# staging rs api
endpoint: "https://rs-calc-stag.ml17.live"
token: <SECRET_TAG>CiQA2N8CmENQeA+WgDVcNjbXdEqf/CEDS8e7p1+siz5jsgqpwqcSTACB1YMgc3bawHF37A8o7Zx5R2IXWVzDMADmfideieAIiv//9fapo2V7IuffaRM48vZP8B6uXdMDqI2s3uz1CPlkP/brxCc8QPTc8ts=</SECRET_TAG>
