### 
#   The variable is to control the notify snapshot service method 
#   when it is liver open/off stream.
#
#   notify value 0 uses PubSub.
#   notify value 1 uses HTTP request.
### 
notify_method: 0

###
#   To do snapshot stream providers.
###
stream_providers:
  - "aws"