redis:
  pre-prod-aggrgateway-cache:
    subscriptionID: "CiQA6Z7kBRB8+2D4PSl/rPZBAoe86K05CgyXqq+vHwfirT6vYpkSMADcvEq6qfPlToPhwhL1oLnVQwFtQ3JffraTZT4fZrVHysB/l8M1Kj7euicIs/3cdA=="
    id: "CiQA6Z7kBcSRBiPDnyL3Vwo+uBrB11X1HCy1S6Kc8X2Ltb5u+xcSMADcvEq6TE03IbcZ5aXsBMTkNHIPpqF28njg0xdCkSYbIxa1ZxP13CBR5reZt+3eqg=="
    usuallySpec: 
      memoryLimitInGb: 1
      throughput: 25000
    stressTestSpec: 
      memoryLimitInGb: 30
      throughput: 25000
  pre-prod-dm-cache:
    subscriptionID: "CiQA6Z7kBapGCB93EPjH6ZymcDEj4zaAbcJs85ggGaeQDKINCJcSMADcvEq6fuquk6c+wxAzgogXmapcYnADPiBJc5mGIThpHXusX84+ERypZz8lRLLIXA=="
    id: "CiQA6Z7kBSOIDdqQuoC3WRkjWyaMUY89FHYY9n+LAHDy5Db0G08SMQDcvEq6SbSpm6CofjZEPaqNXRNz4SkmFmbzBA9Iyb6/DmRvK1xVNe14VSkxANv5l9k="
    usuallySpec: 
      memoryLimitInGb: 2
      throughput: 25000
    stressTestSpec: 
      memoryLimitInGb: 300
      throughput: 275000
mongo: []
