hourLeaderboardDuration:
  start_time: 00h00m00s
  end_time: 24h00m00s
leaderboardCount: 30
opRegion: ["TW"]
enable: true
hotSetting: # Position is 1 based indexing
  maxRankInHot: 10 # Indicate how many top x stars should be put on hot
  newStarsHotPos: [3]
  superStarsHotPos: [1, 4]
new_stars:
- id: 0
  redenvelopeReward: 1
- id: 1
  redenvelopeReward: 1
- id: 2
  redenvelopeReward: 1
- id: 3
  redenvelopeReward: 1
- id: 4
  redenvelopeReward: 1
- id: 5
  redenvelopeReward: 1
- id: 6
  redenvelopeReward: 1
- id: 7
  redenvelopeReward: 1
- id: 8
  redenvelopeReward: 1        
- id: 9
  redenvelopeReward: 1          
super_stars:
- id: 0
  redenvelopeReward: 1
- id: 1
  redenvelopeReward: 1
- id: 2
  redenvelopeReward: 1
- id: 3
  redenvelopeReward: 1
- id: 4
  redenvelopeReward: 1
- id: 5
  redenvelopeReward: 1
- id: 6
  redenvelopeReward: 1
- id: 7
  redenvelopeReward: 1
- id: 8
  redenvelopeReward: 1        
- id: 9
  redenvelopeReward: 1
