# please checkout README.md for further instruction

merchandises:
#shirley test for iOS 日本
  - intervalID: MINV-1ef5HjUfeASnP1HwbOKFVCDHkut
    merchandiseID: media17_giftpackage_tier4
    productsOrder:
      - gift_giftpack_3d_welcome_17_30
      - gift_giftpack_jetcoaster_17_30
      - gift_gift_texture_rabbit_hat_17_30
      - gift_2007_us_supa_bp_17_30
    bonusesOrder:
    addons:
      displayCountdown: true
      countdownSecs: 86400
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/3070b436-9fd0-4e72-8036-193a3317751c.png
      description:
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
    taInfo:
        registerRange:
          dayStart: 0
          dayEnd: 0
        type: 3

#shirley test for Android 日本
  - intervalID: MINV-1ef5HaG7n5yWj2vCTnROqzab69M
    merchandiseID: media17_giftpackage_tier4
    productsOrder:
      - gift_giftpack_3d_welcome_17_30
      - gift_giftpack_jetcoaster_17_30
      - gift_gift_texture_rabbit_hat_17_30
      - gift_2007_us_supa_bp_17_30
    bonusesOrder:
    addons:
      displayCountdown: true
      countdownSecs: 86400
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/3070b436-9fd0-4e72-8036-193a3317751c.png
      description:
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
    taInfo:
        registerRange:
          dayStart: 0
          dayEnd: 0
        type: 3

  #shirley test for iOS
  - intervalID: MINV-1ecwFLbzl3Z3RfTH9t6vjBtlPfC
    merchandiseID: media17_giftpackage_tier1
    productsOrder:
      - barrage_normal_20
      - premiumbaby_30_hrs
    bonusesOrder:
      - gift_giftpack_3d_welcome_9_30
      - gift_giftpack_jetcoaster_17_30
      - gift_2007_us_supa_bp_17_30
      - gift_gift_texture_rabbit_hat_17_30
    addons:
      displayCountdown: true
      countdownSecs: 86400
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/79a3c57d-e3ad-4de8-a3c0-eadb12025e48.png
      description:
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
    abtestName: ""

  #shirley test for Android
  - intervalID: MINV-1ecwFAOg5kOEkeTy63oWGxqPCWT
    merchandiseID: media17_giftpackage_tier1
    productsOrder:
      - barrage_normal_20
      - premiumbaby_30_hrs
    bonusesOrder:
      - gift_giftpack_3d_welcome_9_30
      - gift_giftpack_jetcoaster_17_30
      - gift_2007_us_supa_bp_17_30
      - gift_gift_texture_rabbit_hat_17_30
    addons:
      displayCountdown: true
      countdownSecs: 86400
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/79a3c57d-e3ad-4de8-a3c0-eadb12025e48.png
      description:
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
    abtestName: ""

  # do not modify this one, this is for e2e test
  - intervalID: MINV-1ctP0zCziO87N3HISyMZhRvgTBc
    merchandiseID: media17_points_8550
    productsOrder:
      - barrage_baby_100
      - premiumbaby_168_hrs
    bonusesOrder:
      - gift_arpk_30_14
      - gift_love_you_100_14
      - gift_lovegif_5_14
      - gift_fighting_100_14
    addons:
      displayCountdown: true
      countdownSecs: 36000
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/67882b0c-09ee-429c-be07-92ca3ed8fbab.png
      description:
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_premium_title
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_barrage_title
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
  # for testing
  # media17_points_3540 for IOS
  - intervalID: MINV-1ezkbbv6fIIMlPMfrgrR5sQH5aZ
    merchandiseID: media17_points_3540
    productsOrder:
      - barrage_normal_10
      - premiumbaby_24_hrs
    bonusesOrder:
      - gift_ani_bdf_10_1
      - gift_audio_gift_feel_not_ok_10_1
      - gift_audio_gift_mr_hsu2_10_1
      - gift_audio_gift_feel_ok_10_1
    addons:
      displayCountdown: true
      countdownSecs: 36000
      title:
        key: iap_store_giftpackage_flash
      titleImageURL: https://cdn.17app.co/56c26387-3c8b-47a7-9ea7-dd72023923c1.png
      discountImageURL: https://cdn.17app.co/67882b0c-09ee-429c-be07-92ca3ed8fbab.png
      description:
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
  # media17_points_3540 for android
  - intervalID: MINV-1ezkbY7MbrmSFlQZvuWl8az9toa
    merchandiseID: media17_points_3540
    productsOrder:
      - barrage_normal_10
      - premiumbaby_24_hrs
    bonusesOrder:
      - gift_ani_bdf_10_1
      - gift_audio_gift_feel_not_ok_10_1
      - gift_audio_gift_mr_hsu2_10_1
      - gift_audio_gift_feel_ok_10_1
    addons:
      displayCountdown: true
      countdownSecs: 36000
      title:
        key: iap_store_giftpackage_flash
      titleImageURL: https://cdn.17app.co/56c26387-3c8b-47a7-9ea7-dd72023923c1.png
      discountImageURL: https://cdn.17app.co/67882b0c-09ee-429c-be07-92ca3ed8fbab.png
      description:
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
  # media17_giftpackage_tier1 for IOS
  - intervalID: MINV-1dfJ0oB8lAIVoRnt6mgqKk3xLvu
    merchandiseID: media17_giftpackage_tier1
    productsOrder:
      - barrage_normal_10
      - premiumbaby_24_hrs
    bonusesOrder:
      - gift_ani_bdf_10_1
      - gift_audio_gift_feel_not_ok_10_1
      - gift_audio_gift_mr_hsu2_10_1
      - gift_audio_gift_feel_ok_10_1
    addons:
      displayCountdown: true
      countdownSecs: 1197400
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/67882b0c-09ee-429c-be07-92ca3ed8fbab.png
      description:
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_premium_title
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_barrage_title
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 2
    abtestName: iapPackageTest
  # media17_giftpackage_tier1 for android
  - intervalID: MINV-1dfJ0rZXxl37lZOlrP4zr90BXdq
    merchandiseID: media17_giftpackage_tier1
    productsOrder:
      - barrage_normal_10
      - premiumbaby_24_hrs
    bonusesOrder:
      - gift_ani_bdf_10_1
      - gift_audio_gift_feel_not_ok_10_1
      - gift_audio_gift_mr_hsu2_10_1
      - gift_audio_gift_feel_ok_10_1
    addons:
      displayCountdown: true
      countdownSecs: 1197400
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/67882b0c-09ee-429c-be07-92ca3ed8fbab.png
      description:
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_premium_title
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_barrage_title
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 2
    abtestName: iapPackageTest
  # media17_giftpackage_tier4 for ios
  - intervalID: MINV-1dfIAAV6QE2bwnnhsyKbOEUvAZD
    merchandiseID: media17_giftpackage_tier4
    productsOrder:
      - barrage_baby_10
    bonusesOrder:
      - gift_voucher_daily_reward_gift_cat_3_10_1
    addons:
      displayCountdown: true
      countdownSecs: 1197400
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/67882b0c-09ee-429c-be07-92ca3ed8fbab.png
      description:
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_premium_title
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_barrage_title
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
    abtestName: iapPackageTest
    taInfo:
      registerRange:
        dayStart: 0
        dayEnd: 14
      startTime: "2020-07-03T00:00:00+08:00"
      endTime: "2020-07-03T23:59:59+08:00"
  # media17_giftpackage_tier4 for android
  - intervalID: MINV-1dfIADhAud9N16WynSz2RFINFWP
    merchandiseID: media17_giftpackage_tier4
    productsOrder:
      - barrage_baby_10
    bonusesOrder:
      - gift_voucher_daily_reward_gift_cat_3_10_1
    addons:
      displayCountdown: true
      countdownSecs: 1197400
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/67882b0c-09ee-429c-be07-92ca3ed8fbab.png
      description:
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_premium_title
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_barrage_title
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
    abtestName: iapPackageTest
    taInfo:
      registerRange:
        dayStart: 0
        dayEnd: 14
      startTime: "2020-07-03T00:00:00+08:00"
      endTime: "2020-07-03T23:59:59+08:00"
  # media17_points_1720 for ios
  - intervalID: MINV-1ezLvyAnrPu66ESpclcQPxcZXMF
    merchandiseID: media17_points_1720
    productsOrder:
      - premiumbaby_24_hrs
      - barrage_spaceship_13
    bonusesOrder:
      - gift_daily_reward_love_10_1
      - gift_giftpack_3d_welcome_10_1
      - gift_audio_gift_laughing_1_1
      - gift_audio_gift_clap_1_1
    addons:
      displayCountdown: true
      countdownSecs: 36000
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/67882b0c-09ee-429c-be07-92ca3ed8fbab.png
      description:
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_premium_title
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_barrage_title
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 2
  # media17_points_1720 for android
  - intervalID: MINV-1ezLvuuTrrzPu2IRUo7yiCS3IVa
    merchandiseID: media17_points_1720
    productsOrder:
      - premiumbaby_24_hrs
      - barrage_spaceship_13
    bonusesOrder:
      - gift_daily_reward_love_10_1
      - gift_giftpack_3d_welcome_10_1
      - gift_audio_gift_laughing_1_1
      - gift_audio_gift_clap_1_1
    addons:
      displayCountdown: true
      countdownSecs: 36000
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/67882b0c-09ee-429c-be07-92ca3ed8fbab.png
      description:
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_premium_title
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_barrage_title
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 2
# test for matomo from Janet
  # android
  - intervalID: MINV-1eyuIA5iTQGVWyoYOvwyzdKuVFX
    merchandiseID: media17_giftpackage_tier4
    productsOrder:
      - premiumbaby_48_hrs
      - barrage_baby_10
    bonusesOrder:
      - gift_2004_jp_fairy_streamer_5_1
    addons:
      displayCountdown: true
      countdownSecs: 86400
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/3070b436-9fd0-4e72-8036-193a3317751c.png
      description:
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
  # ios
  - intervalID: MINV-1eyuIADmew0Bq0Lt8b18p2Ydd8X
    merchandiseID: media17_giftpackage_tier4
    productsOrder:
      - premiumbaby_48_hrs
      - barrage_baby_10
    bonusesOrder:
      - gift_2004_jp_fairy_streamer_5_1
    addons:
      displayCountdown: true
      countdownSecs: 86400
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/3070b436-9fd0-4e72-8036-193a3317751c.png
      description:
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1

