iOSATTPermission:
  TW: 
    prompt: true
  JP: 
    prompt: false
  HK:
    prompt: false
  ID:
    prompt: false
  SG:
    prompt: false
  MO:
    prompt: false
  MY:
    prompt: false
  US:
    prompt: false
  MENA:
    prompt: false
  OTHERS:
    prompt: false