iOSATTPermission:
  TW:
    prompt: true
  JP:
    prompt: false
  HK:
    prompt: false
  ID:
    prompt: false
  SG:
    prompt: false
  MO:
    prompt: false
  MY:
    prompt: false
  US:
    prompt: false
  MENA:
    prompt: false
  OTHERS:
    prompt: false

myFollowPage:
  TW:
    showPromotionBanner: true
    showPushNotificationBanner: true
  JP:
    showPromotionBanner: true
    showPushNotificationBanner: true
