iconInfos:
  - startTime: "2023-01-01 00:00:00 (GMT+0900)"
    endTime: "2023-01-16 00:00:00 (GMT+0900)"
    liveIcon:
      activeImg: https://cdn.17app.co/f8b3e9ba-0e5b-4dac-b910-8ff0e034c6ea.png
      disabledImg: https://cdn.17app.co/d8edfeca-3dbb-40dc-8fda-a3b80d5dba82.png
    exploreIcon:
      activeImg: https://cdn.17app.co/775f3847-a3a4-4b10-8d04-ef0e763a81b1.png
      disabledImg: https://cdn.17app.co/bd581796-2ede-43bc-86a9-df7156e33df8.png
    feedIcon:
      activeImg: https://cdn.17app.co/8356bdae-febf-4558-a97e-771622b3d7bf.png
      disabledImg: https://cdn.17app.co/fcb8bb84-a11b-4a41-a67b-e624a3afaf9d.png
    profileIcon:
      activeImg: https://cdn.17app.co/166d952f-1cab-4215-9a4c-c78f376b75cf.png
      disabledImg: https://cdn.17app.co/667a31d2-7122-4cc4-8a4e-506f1763ea39.png
    notificationsIconImg: https://cdn.17app.co/49f4c58b-7eb8-4b00-8223-6e37dccfeeb4.png
    leaderboardIconImg: https://cdn.17app.co/6eff04c0-056e-48f3-bf1e-372f07a7f2f7.png
#サンリオコラボ夏バージョン
  - startTime: 2021-08-01 00:00:00 (GMT+0900)
    endTime: 2021-08-07 23:59:59 (GMT+0900)
    liveIcon:
      activeImg: https://cdn.17app.co/9ddfa376-1918-4aba-b228-6843f08fa289.png
      disabledImg: https://cdn.17app.co/5634f1d8-7262-4207-8dae-37e1f77dd38b.png
    exploreIcon:
      activeImg: https://cdn.17app.co/5d969aa4-2abc-42f5-9ba8-b527c64598ec.png
      disabledImg: https://cdn.17app.co/07f71ccc-9419-4f03-b7e9-0b55812b9ab8.png
    followIcon:
      activeImg:  
      disabledImg:  
    videoIcon:
      activeImg:  
      disabledImg:  
    feedIcon:
      activeImg: https://cdn.17app.co/bccf4603-f8ab-4e03-93a8-e1c8ebf7e551.png
      disabledImg: https://cdn.17app.co/b4ba9daa-e4d5-4b88-bb10-f57fdce4cc92.png
    profileIcon:
      activeImg: https://cdn.17app.co/2efe01c4-9f95-4ed1-bea3-dd819b476e68.png
      disabledImg: https://cdn.17app.co/34c48474-64bb-4523-be33-bed0a7061785.png
    navigationBarBackgroundImg: https://cdn.17app.co/f3b25771-98f5-4ad2-a23f-7c340373b2bc.png
    notificationsIconImg: https://cdn.17app.co/6fcfd3e8-9cbf-4258-b129-ffd0379cbc57.png
    leaderboardIconImg: https://cdn.17app.co/d213bdb3-efa0-417f-8781-3fd3e9129012.png

#2022 xmas
#  - startTime: "2022-12-19 15:00:00 (GMT-0800)"
#    endTime: "2022-12-26 00:00:00 (GMT-0800)"
#    liveIcon:
#      activeImg: https://cdn.17app.co/24c050db-bfa0-4d02-acc2-6551ea793930.png
#      disabledImg: https://cdn.17app.co/1b55aea7-a261-49f8-9afe-38d359b1519a.png
#    exploreIcon:
#      activeImg: https://cdn.17app.co/1aa4d58c-4207-49ce-bd56-2a694f8f67bb.png
#      disabledImg: https://cdn.17app.co/f2c63b78-d525-4d7c-af78-d959a6b06d5f.png
#    feedIcon:
#      activeImg: https://cdn.17app.co/690239e1-e786-463b-a22d-84d9283c5d52.png
#      disabledImg: https://cdn.17app.co/4f4d03b4-1817-4c57-a784-d5cc4dc07e9c.png
#    profileIcon:
#      activeImg: https://cdn.17app.co/e91cd5df-d5ff-495d-92dc-1d928185b294.png
#      disabledImg: https://cdn.17app.co/ce15320b-1e60-434c-8fb2-0215a93b921a.png
#    notificationsIconImg: https://cdn.17app.co/d111106b-c5b8-4e05-b355-09b7fe044e1d.png
#    leaderboardIconImg: https://cdn.17app.co/05aacd9f-3e69-4530-95aa-99c65b21d94e.png

