iconInfos:

  - startTime: 2021-08-01 00:00:00 (GMT+0900)
    endTime: 2021-08-07 23:59:59 (GMT+0900)
    liveIcon:
      activeImg: https://cdn.17app.co/9ddfa376-1918-4aba-b228-6843f08fa289.png
      disabledImg: https://cdn.17app.co/5634f1d8-7262-4207-8dae-37e1f77dd38b.png
    exploreIcon:
      activeImg: https://cdn.17app.co/5d969aa4-2abc-42f5-9ba8-b527c64598ec.png
      disabledImg: https://cdn.17app.co/07f71ccc-9419-4f03-b7e9-0b55812b9ab8.png
    followIcon:
      activeImg:  
      disabledImg:  
    videoIcon:
      activeImg:  
      disabledImg:  
    feedIcon:
      activeImg: https://cdn.17app.co/bccf4603-f8ab-4e03-93a8-e1c8ebf7e551.png
      disabledImg: https://cdn.17app.co/b4ba9daa-e4d5-4b88-bb10-f57fdce4cc92.png
    profileIcon:
      activeImg: https://cdn.17app.co/2efe01c4-9f95-4ed1-bea3-dd819b476e68.png
      disabledImg: https://cdn.17app.co/34c48474-64bb-4523-be33-bed0a7061785.png
    navigationBarBackgroundImg: https://cdn.17app.co/f3b25771-98f5-4ad2-a23f-7c340373b2bc.png
    notificationsIconImg: https://cdn.17app.co/6fcfd3e8-9cbf-4258-b129-ffd0379cbc57.png
    leaderboardIconImg: https://cdn.17app.co/d213bdb3-efa0-417f-8781-3fd3e9129012.png
