iconInfos:
#サンリオコラボ夏バージョン
  - startTime: 2021-08-01 00:00:00 (GMT+0900)
    endTime: 2021-08-07 23:59:59 (GMT+0900)
    liveIcon:
      activeImg: https://cdn.17app.co/9ddfa376-1918-4aba-b228-6843f08fa289.png
      disabledImg: https://cdn.17app.co/5634f1d8-7262-4207-8dae-37e1f77dd38b.png
    exploreIcon:
      activeImg: https://cdn.17app.co/5d969aa4-2abc-42f5-9ba8-b527c64598ec.png
      disabledImg: https://cdn.17app.co/07f71ccc-9419-4f03-b7e9-0b55812b9ab8.png
    followIcon:
      activeImg:  
      disabledImg:  
    videoIcon:
      activeImg:  
      disabledImg:  
    feedIcon:
      activeImg: https://cdn.17app.co/bccf4603-f8ab-4e03-93a8-e1c8ebf7e551.png
      disabledImg: https://cdn.17app.co/b4ba9daa-e4d5-4b88-bb10-f57fdce4cc92.png
    profileIcon:
      activeImg: https://cdn.17app.co/2efe01c4-9f95-4ed1-bea3-dd819b476e68.png
      disabledImg: https://cdn.17app.co/34c48474-64bb-4523-be33-bed0a7061785.png
    navigationBarBackgroundImg: https://cdn.17app.co/f3b25771-98f5-4ad2-a23f-7c340373b2bc.png
    notificationsIconImg: https://cdn.17app.co/6fcfd3e8-9cbf-4258-b129-ffd0379cbc57.png
    leaderboardIconImg: https://cdn.17app.co/d213bdb3-efa0-417f-8781-3fd3e9129012.png

#2022ワールドカップ
  - startTime: "2022-11-30 22:15:00 (GMT+0900)"
    endTime: "2022-12-08 23:59:59 (GMT+0900)"
    liveIcon:
      activeImg: https://cdn.17app.co/fdf7970b-41b2-454d-87e8-e97672fbed4d.png
      disabledImg: https://cdn.17app.co/ef971ec3-d554-4e46-8c38-3375afd8c9ec.png
    exploreIcon:
      activeImg: https://cdn.17app.co/20ddbb29-c7d1-497b-b2d1-8eaa814e8e68.png
      disabledImg: https://cdn.17app.co/0859abeb-9516-47e8-ade5-4810992c4820.png
    feedIcon:
      activeImg: https://cdn.17app.co/c4082156-664e-446d-bd97-dd39b10f7fe8.png
      disabledImg: https://cdn.17app.co/0700c052-3b26-497a-9082-aafe2f31fdf8.png
    profileIcon:
      activeImg: https://cdn.17app.co/8717cde7-66f2-41fd-9a6f-dc275fd8eb17.png
      disabledImg: https://cdn.17app.co/587005e2-e539-4d95-be3c-51c5e5cf16c1.png
    notificationsIconImg: https://cdn.17app.co/e5364403-1937-49f6-a757-476287a6ca4f.png
    leaderboardIconImg: https://cdn.17app.co/4a415194-2404-43e4-b4bc-65a226a2e239.png

