iconInfos:
  - startTime: "2023-01-20 12:00:00 (GMT+0800)" #2023 Chinese New year
    endTime: "2023-01-29 00:00:00 (GMT+0800)"
    liveIcon:
      activeImg: https://cdn.17app.co/bf88dd7b-069e-42e8-9964-e7a0bf1ded23.png
      disabledImg: https://cdn.17app.co/a3290c39-1a95-40e5-84d8-6383903f40f1.png
    exploreIcon:
      activeImg: https://cdn.17app.co/e16dbad2-00b0-4b24-af3d-74c6b6fbacf9.png
      disabledImg: https://cdn.17app.co/ecc1db6c-dba0-464b-8771-d8cd6b8f3d10.png
    feedIcon:
      activeImg: https://cdn.17app.co/87571215-8245-4147-b6a7-e6e8a11eee55.png
      disabledImg: https://cdn.17app.co/ec231cfa-abc6-49e8-acf0-1cbda1f2f5a4.png
    profileIcon:
      activeImg: https://cdn.17app.co/ea6c7776-2904-4812-9640-72eae4fd7870.png
      disabledImg: https://cdn.17app.co/41bc150e-ac7a-473e-9cc1-df2d2cc8e026.png
    notificationsIconImg: https://cdn.17app.co/281a841e-ae5b-4746-bf70-ae2a2dce01d3.png
    leaderboardIconImg: https://cdn.17app.co/f466fbc5-da4d-4f00-927f-c92c4f0f727b.png
    
  - startTime: "2023-01-01 00:00:00 (GMT+0800)"
    endTime: "2023-01-16 00:00:00 (GMT+0800)"
    liveIcon:
      activeImg: https://cdn.17app.co/f8b3e9ba-0e5b-4dac-b910-8ff0e034c6ea.png
      disabledImg: https://cdn.17app.co/d8edfeca-3dbb-40dc-8fda-a3b80d5dba82.png
    exploreIcon:
      activeImg: https://cdn.17app.co/775f3847-a3a4-4b10-8d04-ef0e763a81b1.png
      disabledImg: https://cdn.17app.co/bd581796-2ede-43bc-86a9-df7156e33df8.png
    feedIcon:
      activeImg: https://cdn.17app.co/8356bdae-febf-4558-a97e-771622b3d7bf.png
      disabledImg: https://cdn.17app.co/fcb8bb84-a11b-4a41-a67b-e624a3afaf9d.png
    profileIcon:
      activeImg: https://cdn.17app.co/166d952f-1cab-4215-9a4c-c78f376b75cf.png
      disabledImg: https://cdn.17app.co/667a31d2-7122-4cc4-8a4e-506f1763ea39.png
    notificationsIconImg: https://cdn.17app.co/49f4c58b-7eb8-4b00-8223-6e37dccfeeb4.png
    leaderboardIconImg: https://cdn.17app.co/6eff04c0-056e-48f3-bf1e-372f07a7f2f7.png