iconInfos:
  - startTime: 2021-06-19 18:00:00 (GMT+0800)
    endTime: 2021-08-17 23:59:59 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/c90a55d8-74fa-4bfe-b91e-b869d67fcb44.png
      disabledImg: https://cdn.17app.co/ed1d4368-0660-4d0f-88fe-603af018062d.png
      #disabledImg: https://cdn.17app.co/64b1ac03-ca6c-48a7-bae3-75347c59a708.png
    exploreIcon:
      activeImg: https://cdn.17app.co/fe4c458b-826e-4224-841a-8e1a0cbfb2a2.png
      disabledImg: https://cdn.17app.co/577faf99-7f4d-448c-b7c2-2f1071bd41b7.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/0ac5932d-ec6f-43a4-9087-837ba8fc28d5.png
      disabledImg: https://cdn.17app.co/1936009c-02da-48e1-8ecf-8c9a8469b18e.png
    profileIcon:
      activeImg: https://cdn.17app.co/f9a3800f-83bf-450a-aa1b-55e09bceb304.png
      disabledImg: https://cdn.17app.co/e3bf173e-a8cb-4616-9441-c3f537e41a3c.png
    navigationBarBackgroundImg: https://cdn.17app.co/cc49be76-6f59-48e4-a8cc-72b0eee16e4f.png
    notificationsIconImg: https://cdn.17app.co/b2251e04-0568-463e-a6f1-ea9d466e4621.png
    leaderboardIconImg: https://cdn.17app.co/4ad76eb2-e4be-44ac-8d0c-81b9aaee484b.png



  - startTime: "2021-10-15 18:00:00 (GMT+0800)"
    endTime: "2021-10-31 23:59:59 (GMT+0800)"
    liveIcon:
      activeImg: https://cdn.17app.co/55be4713-417b-416d-b772-e1f2cf25ddfa.png
      disabledImg: https://cdn.17app.co/00d8f3ef-539d-4448-bc46-a7cb55ff075e.png
    exploreIcon:
      activeImg: https://cdn.17app.co/bc810d29-f2a8-48a4-9313-413fccbc879b.png
      disabledImg: https://cdn.17app.co/46b1a77f-c899-4f57-8338-aeef177935e2.png
    feedIcon:
      activeImg: https://cdn.17app.co/d51cae0d-0df8-4fc9-9aa9-eaed9aeae777.png
      disabledImg: https://cdn.17app.co/e0f7ee62-2fd2-44eb-8a0c-165154b0e278.png
    profileIcon:
      activeImg: https://cdn.17app.co/065f2fc2-4177-4093-bdda-6912cfb8f6ab.png
      disabledImg: https://cdn.17app.co/e0788697-53d2-412d-8531-9c94af60aa44.png
    notificationsIconImg: https://cdn.17app.co/dae58671-5ed0-4631-9a4a-a204427041d3.png
    leaderboardIconImg: https://cdn.17app.co/ab80814d-df69-4f54-b54c-33439af745e7.png