iconInfos:
  - startTime: "2023-07-01 00:00:00 (GMT+0800)" #2023 TW Event
    endTime: "2023-08-01 00:00:00 (GMT+0800)"
    liveIcon:
      activeImg: https://cdn.17app.co/de8a3711-131d-43f9-b5f9-a2ac4da35152.png
      disabledImg: https://cdn.17app.co/7aaf1731-3d46-4167-9dd2-3bdbf35b045a.png
    exploreIcon:
      activeImg: https://cdn.17app.co/cac0b882-3c8b-4a08-836d-e8283974af0d.png
      disabledImg: https://cdn.17app.co/9464106c-7412-4e43-9d33-88a675416bc3.png
    feedIcon:
      activeImg: https://cdn.17app.co/34f9028c-f0a1-47e8-b031-25203ed0ccdc.png
      disabledImg: https://cdn.17app.co/d77c613a-b94b-4fa0-b5e5-f9634a9c2306.png
    profileIcon:
      activeImg: https://cdn.17app.co/7477be63-9841-423d-aaed-7e16ef2012e4.png
      disabledImg: https://cdn.17app.co/a572fdf0-d6b6-4314-8950-837f62a4ed08.png
    notificationsIconImg: https://cdn.17app.co/12611168-43a0-487b-bd9c-b9b7a0775e7d.png
    leaderboardIconImg: https://cdn.17app.co/7e572d18-6a84-4ab4-9b24-211c51023af0.png

  - startTime: "2023-06-01 17:30:00 (GMT+0800)" #2023 MKT EXPO
    endTime: "2023-07-01 00:00:00 (GMT+0800)"
    liveIcon:
      activeImg: https://cdn.17app.co/e3cef71a-a967-4462-8be0-9189edc34e6f.png
      disabledImg: https://cdn.17app.co/1c98baf4-6860-48ab-a92c-3a8573229ab4.png
    exploreIcon:
      activeImg: https://cdn.17app.co/d8ae8595-4824-4792-b9de-786ad44e8f21.png
      disabledImg: https://cdn.17app.co/c65598a2-1f9b-4319-ac7d-710a555739da.png
    feedIcon:
      activeImg: https://cdn.17app.co/9cc3f0f2-53b0-4aac-a6ea-6f3b2c825ad7.png
      disabledImg: https://cdn.17app.co/2da2e25e-a9a4-4e5d-a0c2-d52e4815c393.png
    profileIcon:
      activeImg: https://cdn.17app.co/dc8c5c2c-8021-4f7e-a152-1381be96728f.png
      disabledImg: https://cdn.17app.co/dee4003c-fa44-4f35-9d8c-9acff52ac389.png
    notificationsIconImg: https://cdn.17app.co/9bff5fbf-de43-4e04-a2cb-956cdfe5b5bf.png
    leaderboardIconImg: https://cdn.17app.co/e0b0986a-d49a-4c5b-84df-0b2f47c9267b.png
    
  - startTime: "2023-01-01 00:00:00 (GMT+0800)"
    endTime: "2023-01-16 00:00:00 (GMT+0800)"
    liveIcon:
      activeImg: https://cdn.17app.co/f8b3e9ba-0e5b-4dac-b910-8ff0e034c6ea.png
      disabledImg: https://cdn.17app.co/d8edfeca-3dbb-40dc-8fda-a3b80d5dba82.png
    exploreIcon:
      activeImg: https://cdn.17app.co/775f3847-a3a4-4b10-8d04-ef0e763a81b1.png
      disabledImg: https://cdn.17app.co/bd581796-2ede-43bc-86a9-df7156e33df8.png
    feedIcon:
      activeImg: https://cdn.17app.co/8356bdae-febf-4558-a97e-771622b3d7bf.png
      disabledImg: https://cdn.17app.co/fcb8bb84-a11b-4a41-a67b-e624a3afaf9d.png
    profileIcon:
      activeImg: https://cdn.17app.co/166d952f-1cab-4215-9a4c-c78f376b75cf.png
      disabledImg: https://cdn.17app.co/667a31d2-7122-4cc4-8a4e-506f1763ea39.png
    notificationsIconImg: https://cdn.17app.co/49f4c58b-7eb8-4b00-8223-6e37dccfeeb4.png
    leaderboardIconImg: https://cdn.17app.co/6eff04c0-056e-48f3-bf1e-372f07a7f2f7.png
  - startTime: 2022-01-23 11:40:00 (GMT+0800)
    endTime: 2022-01-29 23:59:00 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/939c9c6c-e3b7-4795-b924-2d8b15c6601a.png
      disabledImg: https://cdn.17app.co/93fd8918-8223-420d-8b3e-39e3767e1855.png
    exploreIcon:
      activeImg: https://cdn.17app.co/3e0c216b-8309-468d-a5b5-3fa11602aae7.png
      disabledImg: https://cdn.17app.co/1d7bfd7a-c254-4f36-a048-4668a49eff1f.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/e0ae4604-e2f5-4a18-8745-ca8388ccac2a.png
      disabledImg: https://cdn.17app.co/2f29c6bf-c562-490b-94eb-14716f044321.png
    profileIcon:
      activeImg: https://cdn.17app.co/4462a65b-d0c5-44f6-b7d3-405c29c77d68.png
      disabledImg: https://cdn.17app.co/7cb76fba-cfe3-4e29-a122-1d0810930626.png
    navigationBarBackgroundImg:
    notificationsIconImg: https://cdn.17app.co/692e16ea-a7f0-4791-8e4e-3fc169a85260.png
    leaderboardIconImg: https://cdn.17app.co/5ec27668-b436-47dc-bc79-fe07f17a1979.png

  - startTime: 2022-01-30 10:00:00 (GMT+0800)
    endTime: 2022-02-06 23:59:00 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/a30e2638-e2a3-41c3-b7cb-7da2705ab67e.png
      disabledImg: https://cdn.17app.co/02b32d47-7409-4e74-bd23-b36ab8bed6dd.png
    exploreIcon:      
      activeImg: https://cdn.17app.co/79adeeb6-9ba8-46a0-81c8-70dfd01792b4.png
      disabledImg: https://cdn.17app.co/c313f980-1d7a-42cc-9843-b70cf42cf37d.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/78be5206-f9dc-4025-9d2b-071cebb2cead.png
      disabledImg: https://cdn.17app.co/fb8a3c89-835d-49e1-ae56-70b454540be7.png
    profileIcon:      
      activeImg: https://cdn.17app.co/b63134ed-d29b-4e74-8511-8c7cf8468340.png
      disabledImg: https://cdn.17app.co/8c71f00c-d52b-46a6-a94e-b34193fb7e33.png
    navigationBarBackgroundImg:
    notificationsIconImg: https://cdn.17app.co/05a6d7f2-ed38-442b-be28-797e2e70741d.png
    leaderboardIconImg: https://cdn.17app.co/fb58a447-d5ce-4ad5-b6a5-e1cd396d00c2.png

  - startTime: 2022-04-07 12:00:00 (GMT+0800)
    endTime: 2022-05-31 23:59:59 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/2fa79193-e7c2-42ea-a4de-404e70b01636.png
      disabledImg: https://cdn.17app.co/ab7256c3-7555-4fd0-9209-6a423125da18.png
    exploreIcon:
      activeImg: https://cdn.17app.co/e630e823-4fba-4a72-9519-9217ec2b7963.png
      disabledImg: https://cdn.17app.co/c6f746e3-e04c-4167-b1c6-3198069da56d.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/1d9859f7-6cef-42f6-8d4d-475ab324cce5.png
      disabledImg: https://cdn.17app.co/03b389d3-250f-489a-9606-3cbef13514a2.png
    profileIcon:
      activeImg: https://cdn.17app.co/bbaf60df-2935-4adf-93f2-0b92e81e05e3.png
      disabledImg: https://cdn.17app.co/61e79202-f35b-4abf-8b11-9e9f8c1e31cf.png
    navigationBarBackgroundImg:
    notificationsIconImg: https://cdn.17app.co/632f0fef-f574-4cfa-af3f-79f394e2757f.png
    leaderboardIconImg: https://cdn.17app.co/0ec12433-c92c-4a57-837c-22bd5639e924.png

  - startTime: 2022-06-24 17:30:00 (GMT+0800)
    endTime: 2022-07-31 23:59:59 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/b787ebf7-1ff1-47d1-8822-edf7ffbb814d.png
      disabledImg: https://cdn.17app.co/71f82ef5-6c45-4b20-a258-3e123090dffb.png
    exploreIcon:
      activeImg: https://cdn.17app.co/e35bee92-e27d-46fa-aef9-74ee76f7e1b4.png
      disabledImg: https://cdn.17app.co/52dfc331-9d17-46bc-8332-1e4a11827760.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/1f9ce412-99cc-47f7-af59-79c789899d86.png
      disabledImg: https://cdn.17app.co/b2ef1714-1d93-4b38-bd2d-70db81ca9779.png
    profileIcon:
      activeImg: https://cdn.17app.co/e04eb31b-d9cc-4f43-91aa-a60f1456dea0.png #done change 
      disabledImg: https://cdn.17app.co/789fd07c-8333-436b-80ae-7fedbce284e6.png #done change 
    navigationBarBackgroundImg:
    notificationsIconImg: https://cdn.17app.co/ffe5dc74-5c56-49c7-bd6f-69630579836b.png #done change 
    leaderboardIconImg: https://cdn.17app.co/13fcb64c-38bb-471c-9fe5-939d9ad5b54b.png #done change

  - startTime: "2022-11-24 17:55:00 (GMT+0800)"
    endTime: "2022-12-19 00:00:00 (GMT+0800)"
    liveIcon:
      activeImg: https://cdn.17app.co/fdf7970b-41b2-454d-87e8-e97672fbed4d.png
      disabledImg: https://cdn.17app.co/ef971ec3-d554-4e46-8c38-3375afd8c9ec.png
    exploreIcon:
      activeImg: https://cdn.17app.co/20ddbb29-c7d1-497b-b2d1-8eaa814e8e68.png
      disabledImg: https://cdn.17app.co/0859abeb-9516-47e8-ade5-4810992c4820.png
    feedIcon:
      activeImg: https://cdn.17app.co/c4082156-664e-446d-bd97-dd39b10f7fe8.png
      disabledImg: https://cdn.17app.co/0700c052-3b26-497a-9082-aafe2f31fdf8.png
    profileIcon:
      activeImg: https://cdn.17app.co/8717cde7-66f2-41fd-9a6f-dc275fd8eb17.png
      disabledImg: https://cdn.17app.co/587005e2-e539-4d95-be3c-51c5e5cf16c1.png
    notificationsIconImg: https://cdn.17app.co/e5364403-1937-49f6-a757-476287a6ca4f.png
    leaderboardIconImg: https://cdn.17app.co/99ae94da-e624-418e-bfb0-feabe0c3ffcb.png

  - startTime: "2023-02-10 12:00:00 (GMT+0800)"
    endTime: "2023-05-31 00:00:00 (GMT+0800)"
    liveIcon:
      activeImg: https://cdn.17app.co/5cf2656f-1fbd-4814-b877-19d2d9675cd8.png
      disabledImg: https://cdn.17app.co/c9652403-e0a9-4ea6-b625-e2644c82024b.png
    exploreIcon:
      activeImg: https://cdn.17app.co/d1ebbc75-9c94-491f-a954-55b4b2fb44d4.png
      disabledImg: https://cdn.17app.co/07615f97-9ed5-4829-b832-07a2fd1b2396.png
    feedIcon:
      activeImg: https://cdn.17app.co/555876cf-3a51-4a29-8ed5-088f4d5572cf.png
      disabledImg: https://cdn.17app.co/ea8d2b3d-1b7a-45b1-a917-f85556f3f69e.png
    profileIcon:
      activeImg: https://cdn.17app.co/85a45a19-3703-4612-9924-5ee69d230865.png
      disabledImg: https://cdn.17app.co/43545427-320b-4e5c-8358-d81f0b73480c.png
    notificationsIconImg: https://cdn.17app.co/9acaab17-1dc0-4a4f-9529-0573c8c6fff9.png
    leaderboardIconImg: https://cdn.17app.co/03ca90eb-08c1-4a63-a417-872e2c7ca87a.png

#  - startTime: "2022-12-19 15:00:00 (GMT-0800)"
#    endTime: "2022-12-26 00:00:00 (GMT-0800)"
#    liveIcon:
#      activeImg: https://cdn.17app.co/24c050db-bfa0-4d02-acc2-6551ea793930.png
#      disabledImg: https://cdn.17app.co/1b55aea7-a261-49f8-9afe-38d359b1519a.png
#    exploreIcon:
#      activeImg: https://cdn.17app.co/1aa4d58c-4207-49ce-bd56-2a694f8f67bb.png
#      disabledImg: https://cdn.17app.co/f2c63b78-d525-4d7c-af78-d959a6b06d5f.png
#    feedIcon:
#      activeImg: https://cdn.17app.co/690239e1-e786-463b-a22d-84d9283c5d52.png
#      disabledImg: https://cdn.17app.co/4f4d03b4-1817-4c57-a784-d5cc4dc07e9c.png
#    profileIcon:
#      activeImg: https://cdn.17app.co/e91cd5df-d5ff-495d-92dc-1d928185b294.png
#      disabledImg: https://cdn.17app.co/ce15320b-1e60-434c-8fb2-0215a93b921a.png
#    notificationsIconImg: https://cdn.17app.co/d111106b-c5b8-4e05-b355-09b7fe044e1d.png
#    leaderboardIconImg: https://cdn.17app.co/05aacd9f-3e69-4530-95aa-99c65b21d94e.png