iconInfos:
  - startTime: 2022-01-23 11:40:00 (GMT+0800)
    endTime: 2022-01-29 23:59:00 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/939c9c6c-e3b7-4795-b924-2d8b15c6601a.png
      disabledImg: https://cdn.17app.co/93fd8918-8223-420d-8b3e-39e3767e1855.png
    exploreIcon:
      activeImg: https://cdn.17app.co/3e0c216b-8309-468d-a5b5-3fa11602aae7.png
      disabledImg: https://cdn.17app.co/1d7bfd7a-c254-4f36-a048-4668a49eff1f.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/e0ae4604-e2f5-4a18-8745-ca8388ccac2a.png
      disabledImg: https://cdn.17app.co/2f29c6bf-c562-490b-94eb-14716f044321.png
    profileIcon:
      activeImg: https://cdn.17app.co/4462a65b-d0c5-44f6-b7d3-405c29c77d68.png
      disabledImg: https://cdn.17app.co/7cb76fba-cfe3-4e29-a122-1d0810930626.png
    navigationBarBackgroundImg:
    notificationsIconImg: https://cdn.17app.co/692e16ea-a7f0-4791-8e4e-3fc169a85260.png
    leaderboardIconImg: https://cdn.17app.co/5ec27668-b436-47dc-bc79-fe07f17a1979.png

  - startTime: 2022-01-30 10:00:00 (GMT+0800)
    endTime: 2022-02-06 23:59:00 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/a30e2638-e2a3-41c3-b7cb-7da2705ab67e.png
      disabledImg: https://cdn.17app.co/02b32d47-7409-4e74-bd23-b36ab8bed6dd.png
    exploreIcon:      
      activeImg: https://cdn.17app.co/79adeeb6-9ba8-46a0-81c8-70dfd01792b4.png
      disabledImg: https://cdn.17app.co/c313f980-1d7a-42cc-9843-b70cf42cf37d.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/78be5206-f9dc-4025-9d2b-071cebb2cead.png
      disabledImg: https://cdn.17app.co/fb8a3c89-835d-49e1-ae56-70b454540be7.png
    profileIcon:      
      activeImg: https://cdn.17app.co/b63134ed-d29b-4e74-8511-8c7cf8468340.png
      disabledImg: https://cdn.17app.co/8c71f00c-d52b-46a6-a94e-b34193fb7e33.png
    navigationBarBackgroundImg:
    notificationsIconImg: https://cdn.17app.co/05a6d7f2-ed38-442b-be28-797e2e70741d.png
    leaderboardIconImg: https://cdn.17app.co/fb58a447-d5ce-4ad5-b6a5-e1cd396d00c2.png

  - startTime: 2022-04-07 12:00:00 (GMT+0800)
    endTime: 2022-05-31 23:59:59 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/2fa79193-e7c2-42ea-a4de-404e70b01636.png
      disabledImg: https://cdn.17app.co/ab7256c3-7555-4fd0-9209-6a423125da18.png
    exploreIcon:
      activeImg: https://cdn.17app.co/e630e823-4fba-4a72-9519-9217ec2b7963.png
      disabledImg: https://cdn.17app.co/c6f746e3-e04c-4167-b1c6-3198069da56d.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/1d9859f7-6cef-42f6-8d4d-475ab324cce5.png
      disabledImg: https://cdn.17app.co/03b389d3-250f-489a-9606-3cbef13514a2.png
    profileIcon:
      activeImg: https://cdn.17app.co/bbaf60df-2935-4adf-93f2-0b92e81e05e3.png
      disabledImg: https://cdn.17app.co/61e79202-f35b-4abf-8b11-9e9f8c1e31cf.png
    navigationBarBackgroundImg:
    notificationsIconImg: https://cdn.17app.co/632f0fef-f574-4cfa-af3f-79f394e2757f.png
    leaderboardIconImg: https://cdn.17app.co/0ec12433-c92c-4a57-837c-22bd5639e924.png

  - startTime: 2022-06-24 17:30:00 (GMT+0800)
    endTime: 2022-07-31 23:59:59 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/b787ebf7-1ff1-47d1-8822-edf7ffbb814d.png
      disabledImg: https://cdn.17app.co/71f82ef5-6c45-4b20-a258-3e123090dffb.png
    exploreIcon:
      activeImg: https://cdn.17app.co/e35bee92-e27d-46fa-aef9-74ee76f7e1b4.png
      disabledImg: https://cdn.17app.co/52dfc331-9d17-46bc-8332-1e4a11827760.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/1f9ce412-99cc-47f7-af59-79c789899d86.png
      disabledImg: https://cdn.17app.co/b2ef1714-1d93-4b38-bd2d-70db81ca9779.png
    profileIcon:
      activeImg: https://cdn.17app.co/e04eb31b-d9cc-4f43-91aa-a60f1456dea0.png #done change 
      disabledImg: https://cdn.17app.co/789fd07c-8333-436b-80ae-7fedbce284e6.png #done change 
    navigationBarBackgroundImg:
    notificationsIconImg: https://cdn.17app.co/ffe5dc74-5c56-49c7-bd6f-69630579836b.png #done change 
    leaderboardIconImg: https://cdn.17app.co/13fcb64c-38bb-471c-9fe5-939d9ad5b54b.png #done change 