iconInfos:
  - startTime: 2022-01-23 12:00:00 (GMT+0800)
    endTime: 2022-01-29 23:59:00 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/939c9c6c-e3b7-4795-b924-2d8b15c6601a.png
      disabledImg: https://cdn.17app.co/8c6bff77-0ccb-4ffd-bf76-71a784312385.png
    exploreIcon:
      activeImg: https://cdn.17app.co/3e0c216b-8309-468d-a5b5-3fa11602aae7.png
      disabledImg: https://cdn.17app.co/3e0c216b-8309-468d-a5b5-3fa11602aae7.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/e0ae4604-e2f5-4a18-8745-ca8388ccac2a.png
      disabledImg: https://cdn.17app.co/e0ae4604-e2f5-4a18-8745-ca8388ccac2a.png
    profileIcon:
      activeImg: https://cdn.17app.co/4462a65b-d0c5-44f6-b7d3-405c29c77d68.png
      disabledImg: https://cdn.17app.co/ad386ed5-0c33-43f7-98b9-e2edb4dc30b5.png
    navigationBarBackgroundImg:
    notificationsIconImg: https://cdn.17app.co/692e16ea-a7f0-4791-8e4e-3fc169a85260.png
    leaderboardIconImg: https://cdn.17app.co/5ec27668-b436-47dc-bc79-fe07f17a1979.png

  - startTime: 2021-01-30 00:00:00 (GMT+0800)
    endTime: 2021-02-06 23:59:00 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/a30e2638-e2a3-41c3-b7cb-7da2705ab67e.png
      disabledImg: https://cdn.17app.co/02b32d47-7409-4e74-bd23-b36ab8bed6dd.png
    exploreIcon:      
      activeImg: https://cdn.17app.co/79adeeb6-9ba8-46a0-81c8-70dfd01792b4.png      
      disabledImg: https://cdn.17app.co/c313f980-1d7a-42cc-9843-b70cf42cf37d.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/78be5206-f9dc-4025-9d2b-071cebb2cead.png
      disabledImg: https://cdn.17app.co/fb8a3c89-835d-49e1-ae56-70b454540be7.png
    profileIcon:      
      activeImg: https://cdn.17app.co/b63134ed-d29b-4e74-8511-8c7cf8468340.png
      disabledImg: https://cdn.17app.co/8c71f00c-d52b-46a6-a94e-b34193fb7e33.png
    navigationBarBackgroundImg:    
    notificationsIconImg: https://cdn.17app.co/05a6d7f2-ed38-442b-be28-797e2e70741d.png
    leaderboardIconImg: https://cdn.17app.co/fb58a447-d5ce-4ad5-b6a5-e1cd396d00c2.png