iconInfos:
  - startTime: 2022-01-23 12:00:00 (GMT+0800)
    endTime: 2022-01-29 23:59:59 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/939c9c6c-e3b7-4795-b924-2d8b15c6601a.png
      disabledImg: https://cdn.17app.co/8c6bff77-0ccb-4ffd-bf76-71a784312385.png
    exploreIcon:
      activeImg: https://cdn.17app.co/3e0c216b-8309-468d-a5b5-3fa11602aae7.png
      disabledImg: https://cdn.17app.co/3e0c216b-8309-468d-a5b5-3fa11602aae7.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/e0ae4604-e2f5-4a18-8745-ca8388ccac2a.png
      disabledImg: https://cdn.17app.co/e0ae4604-e2f5-4a18-8745-ca8388ccac2a.png
    profileIcon:
      activeImg: https://cdn.17app.co/4462a65b-d0c5-44f6-b7d3-405c29c77d68.png
      disabledImg: https://cdn.17app.co/ad386ed5-0c33-43f7-98b9-e2edb4dc30b5.png
    navigationBarBackgroundImg:
    notificationsIconImg: https://cdn.17app.co/692e16ea-a7f0-4791-8e4e-3fc169a85260.png
    leaderboardIconImg: https://cdn.17app.co/5ec27668-b436-47dc-bc79-fe07f17a1979.png