hourLeaderboardDuration:
start_time: 00h00m00s
end_time: 24h00m00s
leaderboardCount: 30
opRegion: ["TW"]
enable: true
hotSetting:
  maxRankInHot: 10 # Indicate how many top x stars should be put on hot
  newStarsHotPos: [3]
  superStarsHotPos: [1, 4]
new_stars:
- id: 0
  redenvelopeReward: 12
- id: 1
  redenvelopeReward: 6
- id: 2
  redenvelopeReward: 6
- id: 3
  redenvelopeReward: 6
- id: 4
  redenvelopeReward: 6
- id: 5
  redenvelopeReward: 6
- id: 6
  redenvelopeReward: 6
- id: 7
  redenvelopeReward: 6
- id: 8
  redenvelopeReward: 6        
- id: 9
  redenvelopeReward: 6          
super_stars:
- id: 0
  redenvelopeReward: 12
- id: 1
  redenvelopeReward: 6
- id: 2
  redenvelopeReward: 6
- id: 3
  redenvelopeReward: 6
- id: 4
  redenvelopeReward: 6
- id: 5
  redenvelopeReward: 6
- id: 6
  redenvelopeReward: 6
- id: 7
  redenvelopeReward: 6
- id: 8
  redenvelopeReward: 6        
- id: 9
  redenvelopeReward: 6
