hourLeaderboardDuration:
start_time: 00h00m00s
end_time: 24h00m00s
leaderboardCount: 30
opRegion: ["TW"]
enable: true
hotSetting:
  maxRankInHot: 10 # Indicate how many top x stars should be put on hot
  newStarsHotPos: [2]
  superStarsHotPos: [0, 3]
new_stars:
- id: 0
  position: 3
  redenvelopeReward: 12
- id: 1
  position: 0
  redenvelopeReward: 6
- id: 2
  position: 0
  redenvelopeReward: 6
- id: 3
  position: 0
  redenvelopeReward: 6
- id: 4
  position: 0
  redenvelopeReward: 6
- id: 5
  position: 0
  redenvelopeReward: 6
- id: 6
  position: 0
  redenvelopeReward: 6
- id: 7
  position: 0
  redenvelopeReward: 6
- id: 8
  position: 0
  redenvelopeReward: 6        
- id: 9
  position: 0
  redenvelopeReward: 6          
super_stars:
- id: 0
  position: 1
  redenvelopeReward: 12
- id: 1
  position: 4
  redenvelopeReward: 6
- id: 2
  position: 0
  redenvelopeReward: 6
- id: 3
  position: 0
  redenvelopeReward: 6
- id: 4
  position: 0
  redenvelopeReward: 6
- id: 5
  position: 0
  redenvelopeReward: 6
- id: 6
  position: 0
  redenvelopeReward: 6
- id: 7
  position: 0
  redenvelopeReward: 6
- id: 8
  position: 0
  redenvelopeReward: 6        
- id: 9
  position: 0
  redenvelopeReward: 6
