type:
  revprox:      "go"
  goapi:        "go"
  cronjob:      "go"
  notif:        "go"
  slackbot:     "go"
  shield:       "go"
  skyeye:       "go"
  bdapi:        "go"
  mktevent:     "go"
  event-server: "go"
  worker:       "go"
  nodejs:       "nodejs"
  admin:        "nodejs"
  webapp:       "webapp"
  skyeyewall:   "webapp"
  17live:       "webapp"
settings:
  go:
    k8ssta:
      endpoint: 'https://admin-bot:efXtJASgYHxz7wCx23fH@jenkins.17app.co/job/k8ssta-deployment-goapi/buildWithParameters?token=qLnZFhgbtDwYHq3bpqdsfHkXqEbMS7VAuTshkBrQ'
    k8sprod:
      endpoint: 'https://admin-bot:efXtJASgYHxz7wCx23fH@jenkins.17app.co/job/k8sprod-deployment-goapi/buildWithParameters?token=WPZgd7ag4Q7ksL3nSqLW2QVq6aaDK5apguCvR23M'
    sta:
      endpoint: 'https://admin-bot:efXtJASgYHxz7wCx23fH@jenkins.17app.co/job/sta-deployment-goapi/buildWithParameters?token=qLnZFhgbtDwYHq3bpqdsfHkXqEbMS7VAuTshkBrQ'
    prod:
      endpoint: 'https://admin-bot:efXtJASgYHxz7wCx23fH@jenkins.17app.co/job/prod-deployment-goapi/buildWithParameters?token=qk22aAD29Fp9AT4n5MDrwJBg4tybpgZtNtdqZ3vg'
