max: 1	# 0 means disable feature
check_interval: 1m00s
big_brother_prefix: "big_brother"
ccu: 0
streamDuration: 0h00m00s
animations : ["yeti","big_brother"]
monsters:
- id: monster_1
  hit_consume: 10
  duration: 30s
  stream_alive_threshold: 1m00s
  animation: "yeti"
  appear_durations:
  - start_time: 00h00m00s
    end_time: 24h00m00s
  share_ratio: 50 # percentage
  profit_ratio: 24 # percentage
  bonus: 200
  infoPageiconURL: https://assets-17app.akamaized.net/d1d67cab-3f7b-439f-86d8-aed1cf327fdb.png
  winnerPageiconURL: https://assets-17app.akamaized.net/9b0cf5bc-8289-4af0-b7d4-41869506db6a.png
  hintToken: {key: monster_battle_hint,fontAttribute: {textColor: "#FFFFFF"}}
  rule1Token: {key: monster_battle_rule1,fontAttribute: {textColor: "#FFFFFF"}}
  rule2Token: {key: monster_battle_rule2,fontAttribute: {textColor: "#FFFFFF"}}
  rule3Token: {key: monster_battle_rule3,fontAttribute: {textColor: "#FFFFFF"}} 
  rule4Token: {key: monster_battle_rule4,fontAttribute: {textColor: "#FFFFFF"}}
  countdownToken: {key: monster_battle_countdown,fontAttribute: {textColor: "#FFFFFF"}}
  failureToken: {key: monster_battle_failure,fontAttribute: {textColor: "#FFFFFF"}}


- id: monster_2
  animation: "give_me_five"
  hit_consume: 10
  duration: 30s
  stream_alive_threshold: 1m00s
  appear_durations:
  - start_time: 00h00m00s
    end_time: 2h00m00s
  - start_time: 12h00m00s
    end_time: 14h30m00s
  - start_time: 17h00m00s
    end_time: 24h00m00s
  share_ratio: 50 # percentage
  profit_ratio: 24 # percentage
  bonus: 300
  infoPageiconURL: https://assets-17app.akamaized.net/0e302f14-4bc4-4031-8f10-1623bd311c00.png
  winnerPageiconURL: https://assets-17app.akamaized.net/724adf04-816f-484d-bd8b-ddb0346e8513.png
  hintToken: {key: monster_battle_hint_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  rule1Token: {key: monster_battle_rule1_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  rule2Token: {key: monster_battle_rule2_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  rule3Token: {key: monster_battle_rule3_bbro,fontAttribute: {textColor: "#FFFFFF"}} 
  rule4Token: {key: monster_battle_rule4_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  countdownToken: {key: monster_battle_countdown_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  failureToken: {key: monster_battle_failure_bbro,fontAttribute: {textColor: "#FFFFFF"}}


- id: monster_3
  animation: "give_me_five"
  hit_consume: 10
  duration: 30s
  stream_alive_threshold: 1m00s
  appear_durations:
  - start_time: 00h00m00s
    end_time: 2h00m00s
  - start_time: 12h00m00s
    end_time: 14h30m00s
  - start_time: 17h00m00s
    end_time: 24h00m00s
  share_ratio: 50 # percentage
  profit_ratio: 24 # percentage
  bonus: 4000
  infoPageiconURL: https://assets-17app.akamaized.net/0e302f14-4bc4-4031-8f10-1623bd311c00.png
  winnerPageiconURL: https://assets-17app.akamaized.net/724adf04-816f-484d-bd8b-ddb0346e8513.png
  hintToken: {key: monster_battle_hint_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  rule1Token: {key: monster_battle_rule1_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  rule2Token: {key: monster_battle_rule2_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  rule3Token: {key: monster_battle_rule3_bbro,fontAttribute: {textColor: "#FFFFFF"}} 
  rule4Token: {key: monster_battle_rule4_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  countdownToken: {key: monster_battle_countdown_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  failureToken: {key: monster_battle_failure_bbro,fontAttribute: {textColor: "#FFFFFF"}}


- id: monster_4
  hit_consume: 10
  duration: 30s
  animation: "give_me_five"
  stream_alive_threshold: 1m00s
  appear_durations:
  - start_time: 00h00m00s
    end_time: 2h00m00s
  - start_time: 12h00m00s
    end_time: 14h30m00s
  - start_time: 17h00m00s
    end_time: 24h00m00s
  share_ratio: 50 # percentage
  profit_ratio: 24 # percentage
  bonus: 500
  infoPageiconURL: https://assets-17app.akamaized.net/0e302f14-4bc4-4031-8f10-1623bd311c00.png
  winnerPageiconURL: https://assets-17app.akamaized.net/724adf04-816f-484d-bd8b-ddb0346e8513.png
  hintToken: {key: monster_battle_hint_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  rule1Token: {key: monster_battle_rule1_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  rule2Token: {key: monster_battle_rule2_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  rule3Token: {key: monster_battle_rule3_bbro,fontAttribute: {textColor: "#FFFFFF"}} 
  rule4Token: {key: monster_battle_rule4_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  countdownToken: {key: monster_battle_countdown_bbro,fontAttribute: {textColor: "#FFFFFF"}}
  failureToken: {key: monster_battle_failure_bbro,fontAttribute: {textColor: "#FFFFFF"}}


- id: monster_5
  hit_consume: 10
  duration: 30s
  animation: "yeti"
  stream_alive_threshold: 1m00s
  appear_durations:
  - start_time: 00h00m00s
    end_time: 2h00m00s
  - start_time: 12h00m00s
    end_time: 14h30m00s
  - start_time: 17h00m00s
    end_time: 24h00m00s
  share_ratio: 50 # percentage
  profit_ratio: 24 # percentage
  bonus: 600
  infoPageiconURL: https://assets-17app.akamaized.net/d1d67cab-3f7b-439f-86d8-aed1cf327fdb.png
  winnerPageiconURL: https://assets-17app.akamaized.net/9b0cf5bc-8289-4af0-b7d4-41869506db6a.png
  hintToken: {key: monster_battle_hint,fontAttribute: {textColor: "#FFFFFF"}}
  rule1Token: {key: monster_battle_rule1,fontAttribute: {textColor: "#FFFFFF"}}
  rule2Token: {key: monster_battle_rule2,fontAttribute: {textColor: "#FFFFFF"}}
  rule3Token: {key: monster_battle_rule3,fontAttribute: {textColor: "#FFFFFF"}} 
  rule4Token: {key: monster_battle_rule4,fontAttribute: {textColor: "#FFFFFF"}}
  countdownToken: {key: monster_battle_countdown,fontAttribute: {textColor: "#FFFFFF"}}
  failureToken: {key: monster_battle_failure,fontAttribute: {textColor: "#FFFFFF"}}


- id: monster_6
  hit_consume: 10
  duration: 30s
  animation: "yeti"
  stream_alive_threshold: 1m00s
  appear_durations:
  - start_time: 00h00m00s
    end_time: 2h00m00s
  - start_time: 12h00m00s
    end_time: 14h30m00s
  - start_time: 17h00m00s
    end_time: 24h00m00s
  share_ratio: 50 # percentage
  profit_ratio: 24 # percentage
  bonus: 700
  infoPageiconURL: https://assets-17app.akamaized.net/d1d67cab-3f7b-439f-86d8-aed1cf327fdb.png
  winnerPageiconURL: https://assets-17app.akamaized.net/9b0cf5bc-8289-4af0-b7d4-41869506db6a.png
  hintToken: {key: monster_battle_hint,fontAttribute: {textColor: "#FFFFFF"}}
  rule1Token: {key: monster_battle_rule1,fontAttribute: {textColor: "#FFFFFF"}}
  rule2Token: {key: monster_battle_rule2,fontAttribute: {textColor: "#FFFFFF"}}
  rule3Token: {key: monster_battle_rule3,fontAttribute: {textColor: "#FFFFFF"}} 
  rule4Token: {key: monster_battle_rule4,fontAttribute: {textColor: "#FFFFFF"}}
  countdownToken: {key: monster_battle_countdown,fontAttribute: {textColor: "#FFFFFF"}}
  failureToken: {key: monster_battle_failure,fontAttribute: {textColor: "#FFFFFF"}}

  
- id: monster_7
  hit_consume: 10
  duration: 30s
  animation: "yeti"
  stream_alive_threshold: 1m00s
  appear_durations:
  - start_time: 00h00m00s
    end_time: 2h00m00s
  - start_time: 12h00m00s
    end_time: 14h30m00s
  - start_time: 17h00m00s
    end_time: 24h00m00s
  share_ratio: 50 # percentage
  profit_ratio: 24 # percentage
  bonus: 800
  infoPageiconURL: https://assets-17app.akamaized.net/d1d67cab-3f7b-439f-86d8-aed1cf327fdb.png
  winnerPageiconURL: https://assets-17app.akamaized.net/9b0cf5bc-8289-4af0-b7d4-41869506db6a.png
  hintToken: {key: monster_battle_hint,fontAttribute: {textColor: "#FFFFFF"}}
  rule1Token: {key: monster_battle_rule1,fontAttribute: {textColor: "#FFFFFF"}}
  rule2Token: {key: monster_battle_rule2,fontAttribute: {textColor: "#FFFFFF"}}
  rule3Token: {key: monster_battle_rule3,fontAttribute: {textColor: "#FFFFFF"}} 
  rule4Token: {key: monster_battle_rule4,fontAttribute: {textColor: "#FFFFFF"}}
  countdownToken: {key: monster_battle_countdown,fontAttribute: {textColor: "#FFFFFF"}}
  failureToken: {key: monster_battle_failure,fontAttribute: {textColor: "#FFFFFF"}}


animationLoader:
- url: https://assets-17app.akamaized.net/2be7d636-3e8c-4a8b-8ca6-bb80b0528a3a.zip
  webpUrl: https://assets-17app.akamaized.net/d679eb31-e6d9-456c-a32e-9551fed77bf6-q90-s1.webp
  animationID: yeti_attack
  MD5: f1db4dba3ecc635ffbf00f1c90b11254
  webpMD5: 7de51dc2b2863ae56820a9daa54e2521
- url: https://assets-17app.akamaized.net/7706eba5-56e3-4a46-8b38-27ea83bfd247.zip
  webpUrl: https://assets-17app.akamaized.net/31539154-3931-496f-9c3a-9b14b00c9084-q90-s1.webp
  animationID: yeti_enter
  MD5: 085e649d33ff18195638db0676297540    
  webpMD5: 0436df384fc36d9160ed091bebff916e 
- url: https://assets-17app.akamaized.net/3c1bb8db-2d6e-4e69-88fa-71ba918cfecc.zip
  webpUrl: https://assets-17app.akamaized.net/6e9f5adb-51f7-4616-977d-19b24f948a9d-q90-s1.webp
  animationID: yeti_failure
  MD5: 4cce1c0c875f5474c155852877b63225 
  webpMD5: 4ad8a1028c624cc1246b369c239953e7 
- url: https://assets-17app.akamaized.net/82f42040-bba8-4a39-af8d-4e98cb328620.zip
  webpUrl: https://assets-17app.akamaized.net/27048f58-09fc-44ea-af46-e3444002663b-q90-s1.webp
  animationID: yeti_idle
  MD5: 296eb4e6eabea2f342c6fa543da32e62
  webpMD5: 88b5ea9f2f0eba52d53be1c93da7955a
- url: https://assets-17app.akamaized.net/faf1316f-ea42-49cc-8f1e-56aca5fadc27.zip
  webpUrl: https://assets-17app.akamaized.net/7a56b6eb-13f6-4f90-afcb-591c63da47b2-q90-s1.webp
  animationID: yeti_success
  MD5: 4db3f6b14ade0a938a689a27b23bd330
  webpMD5: 7e8bc69aab41d3949f4bb9560d5000eb 
- url: https://assets-17app.akamaized.net/f14f8f44-c6b5-456e-ba66-e02d13dc0ac4.zip
  webpUrl: https://assets-17app.akamaized.net/a0ec4825-3dc7-4b38-b6aa-5d82b11f84be-q90-s1.webp
  animationID: give_me_five_attack
  MD5: 51cb515ac54ee194fc20525f45ceef8c
  webpMD5: 7c4fb9832e0fd34c450d56f662028413
- url: https://assets-17app.akamaized.net/a497075e-dfb6-426f-9de5-dca8f9d2a75d.zip
  webpUrl: https://assets-17app.akamaized.net/5703f137-429b-4e3c-bc2f-6ad5e39783fc-q90-s1.webp
  animationID: give_me_five_enter
  MD5: d475e832eb160a10d178a84ab0e2d455  
  webpMD5: 9ba611705f77f0516b0874b50b1eecc9   
- url: https://assets-17app.akamaized.net/fe7a7d3b-a5e3-4f31-9bee-fe845fc12a5a.zip
  webpUrl: https://assets-17app.akamaized.net/f0d8f499-ba91-4c99-aabb-e422739613f4-q90-s1.webp
  animationID: give_me_five_failure
  MD5: a2311f4ef51d2bbe49d23a07b536e29d
  webpMD5: 506b47738a306d62ef04ad7cccb3596d 
- url: https://assets-17app.akamaized.net/7b170fe1-bef0-4bc3-86a7-78a9efdad6a1.zip
  webpUrl: https://assets-17app.akamaized.net/3d9afdbb-03e2-4976-a79d-1d2bd0a6678d-q90-s1.webp
  animationID: give_me_five_idle
  MD5: b985e36ebb56ae361b6e2a0c9f84244b
  webpMD5: 834794e2707bdac50c7fd1ab611b3743
- url: https://assets-17app.akamaized.net/f8cc6c60-b9e3-479a-a269-7ecba1915442.zip
  webpUrl: https://assets-17app.akamaized.net/8ff8927d-8ffa-4841-9658-ce0a9b4103ff-q90-s1.webp
  animationID: give_me_five_success
  MD5: 9051102069021748b33fc1052dc8f7ca     
  webpMD5: fd3ab7d2aa10dde39e118a4e9c724f7a
