# please checkout README.md for further instruction

merchandises:
# 2020-07-15 新手首儲大禮包_iOS
  - intervalID: MINV-1eht3GYgtpbViwRRwdPj591qWi6
    merchandiseID: media17_giftpackage_tier1
    productsOrder:
      - barrage_normal_20
      - premiumbaby_720_hrs
    bonusesOrder:
      - gift_giftpack_3d_welcome_9_30
      - gift_giftpack_jetcoaster_17_30
      - gift_giftpack_audio_gift_catkiss_17_30
      - gift_gift_texture_rabbit_hat_17_30
    addons:
      displayCountdown: false
      countdownSecs: 86400
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/79a3c57d-e3ad-4de8-a3c0-eadb12025e48.png
      description:
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
    taInfo:
        registerRange:
          dayStart: 0
          dayEnd: 14
        type: 3
    abtestName: "iapPromotion"

# 2020-07-15 新手首儲大禮包_Android
  - intervalID: MINV-1eht3GNlgjVhIxuX4ljs5xdLq2o
    merchandiseID: media17_giftpackage_tier1
    productsOrder:
      - barrage_normal_20
      - premiumbaby_720_hrs
    bonusesOrder:
      - gift_giftpack_3d_welcome_9_30
      - gift_giftpack_jetcoaster_17_30
      - gift_giftpack_audio_gift_catkiss_17_30
      - gift_gift_texture_rabbit_hat_17_30
    addons:
      displayCountdown: false
      countdownSecs: 86400
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/79a3c57d-e3ad-4de8-a3c0-eadb12025e48.png
      description:
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
    taInfo:
        registerRange:
          dayStart: 0
          dayEnd: 14
        type: 3
    abtestName: "iapPromotion"