# please checkout README.md for further instruction
#purchaseType: 1限購一次;2不限
#type受眾群體: 1判斷時間區段沒有購買過; 2判斷時間區段有購買過; 3生涯沒有購買過(任何購買記錄都算); 4生涯有購買過

merchandises:
#B2B新手禮包_iOS
  - intervalID: MINV-1kVA0x1mlVUinam0Gafdrmk5B45
    merchandiseID: media17_giftpackage_tier5_202011_tw #對google play / app store的id
    productsOrder: #product的順序，product不可為0
      - barrage_normal_10
    bonusesOrder: #bonus的順序，如果只有bouns請移至productOrder
      - life3d_gmorning
      - life3d_gafternoon
      - life3d_gnight
      - giftpack_3d_welcome
      - giftpack_jetcoaster
      - giftpack_audio_gift_catkiss
      - gift_texture_rabbit_hat
    addons:
      displayCountdown: false
      #要不要顯示倒數計時
      countdownSecs: 86400
      #距離結束時間多少以前開始 highlight
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/79a3c57d-e3ad-4de8-a3c0-eadb12025e48.png
      description:
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
    taInfo: #受眾
        registerRange:
          dayStart: 0
          #若為0則不受限制
          dayEnd: 14
        type: 3
        startTime: #受眾的判斷時間開始時間, 不是禮包的有效時間,若沒有值則不受限制
        endTime: #受眾的判斷時間結束時間, 不是禮包的結束時間,若沒有值則不受限制
    abtestName: "" #禮包測試相關的abtest名稱, 需要 abtest.yaml也做相關的設定

#B2B新手禮包_Android
  - intervalID: MINV-1kVA0ucnBmOWvfNjZZkvmaboSLI
    merchandiseID: media17_giftpackage_tier5_202011_tw
    productsOrder:
      - barrage_normal_10
    bonusesOrder: #bonus的順序，如果只有bouns請移至productOrder
      - life3d_gmorning
      - life3d_gafternoon
      - life3d_gnight
      - giftpack_3d_welcome
      - giftpack_jetcoaster
      - giftpack_audio_gift_catkiss
      - gift_texture_rabbit_hat
    addons:
      displayCountdown: false
      countdownSecs: 86400
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/79a3c57d-e3ad-4de8-a3c0-eadb12025e48.png
      description:
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
    taInfo:
        registerRange:
          dayStart: 0
          dayEnd: 14
        type: 3
    abtestName: ""

# 新手首儲大禮包_iOS
#  - intervalID: MINV-1eht3GYgtpbViwRRwdPj591qWi6  #(07/15)   #禮包內部的 id
  - intervalID: MINV-1eht3KdRJCDfOVg2n5G0NYR00oL
    merchandiseID: media17_giftpackage_tier1
    #對google play / app store的id
    productsOrder: #product的順序，product不可為0
      - barrage_normal_20
      - premiumbaby_720_hrs
    bonusesOrder: #bonus的順序，如果只有bouns請移至productOrder
      - gift_giftpack_3d_welcome_9_30
      - gift_giftpack_jetcoaster_17_30
      - gift_giftpack_audio_gift_catkiss_17_30
      - gift_gift_texture_rabbit_hat_17_30
    addons:
      displayCountdown: false
      #要不要顯示倒數計時
      countdownSecs: 86400
      #距離結束時間多少以前開始 highlight
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/79a3c57d-e3ad-4de8-a3c0-eadb12025e48.png
      description:
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
    taInfo: #受眾
        registerRange:
          dayStart: 0
          #若為0則不受限制
          dayEnd: 14
        type: 3
        startTime: #受眾的判斷時間開始時間, 不是禮包的有效時間,若沒有值則不受限制
        endTime: #受眾的判斷時間結束時間, 不是禮包的結束時間,若沒有值則不受限制
    abtestName: "" #禮包測試相關的abtest名稱, 需要 abtest.yaml也做相關的設定

# 新手首儲大禮包_Android
#  - intervalID: MINV-1eht3GNlgjVhIxuX4ljs5xdLq2o #(07/15)
  - intervalID: MINV-1eht3MEcbH3lxMzxrozgPWn3Jk2
    merchandiseID: media17_giftpackage_tier1
    productsOrder:
      - barrage_normal_20
      - premiumbaby_720_hrs
    bonusesOrder:
      - gift_giftpack_3d_welcome_9_30
      - gift_giftpack_jetcoaster_17_30
      - gift_giftpack_audio_gift_catkiss_17_30
      - gift_gift_texture_rabbit_hat_17_30
    addons:
      displayCountdown: false
      countdownSecs: 86400
      title:
        key: iap_store_giftpackage_newbie
      titleImageURL: https://cdn.17app.co/392ead48-62dc-4321-9a86-923458ce19ab.png
      discountImageURL: https://cdn.17app.co/79a3c57d-e3ad-4de8-a3c0-eadb12025e48.png
      description:
        - imageURL: https://cdn.17app.co/829a6a48-ab1a-4f06-bc96-80630aa13083.png
          text:
            key: iap_store_giftpackage_dialog_premium_desc
        - imageURL: https://cdn.17app.co/8cab3332-2e53-48e2-a588-dc469b091641.png
          text:
            key: iap_store_giftpackage_dialog_barrage_desc
        - imageURL:
          text:
            key: iap_store_giftpackage_dialog_gift_desc
    purchaseType: 1
    taInfo:
        registerRange:
          dayStart: 0
          dayEnd: 14
        type: 3
    abtestName: ""
