iconInfos:
  - startTime: "2023-02-06 12:00:00 (GMT+0800)" #2023 V Day
    endTime: "2023-02-15 00:00:00 (GMT+0800)"
    liveIcon:
      activeImg: https://cdn.17app.co/17f0ae09-f78b-4854-8f2b-f1694e8a7d35.png
      disabledImg: https://cdn.17app.co/43937fd9-0c8b-4cec-96bf-4b89902781a3.png
    exploreIcon:
      activeImg: https://cdn.17app.co/c3a298e8-96af-494e-8a0c-5144c039d042.png
      disabledImg: https://cdn.17app.co/df7d84da-fd1d-48d4-9c0e-a0aa7770f3dd.png
    feedIcon:
      activeImg: https://cdn.17app.co/1ec3b6e3-d123-4ce9-a937-244c48c7ae29.png
      disabledImg: https://cdn.17app.co/52febf74-912c-406a-a9de-3598be967d78.png
    profileIcon:
      activeImg: https://cdn.17app.co/f332cc79-3dc0-4844-89d7-54bcc7c3f791.png
      disabledImg: https://cdn.17app.co/8e18b30d-c4d7-478f-8f4b-0d2348c10ec8.png
    notificationsIconImg: https://cdn.17app.co/184d1eb5-f5bf-436e-a71a-1e84a03617d2.png
    leaderboardIconImg: https://cdn.17app.co/4fc6afd4-d699-4446-8e7e-86baaadabec0.png
    
  - startTime: 2021-12-02 17:50:00 (GMT+0800)
    endTime: 2021-12-31 23:59:00 (GMT+0800)
    liveIcon:
      activeImg: https://cdn.17app.co/a30e2638-e2a3-41c3-b7cb-7da2705ab67e.png
      disabledImg: https://cdn.17app.co/02b32d47-7409-4e74-bd23-b36ab8bed6dd.png
    exploreIcon:
      activeImg: https://cdn.17app.co/79adeeb6-9ba8-46a0-81c8-70dfd01792b4.png
      disabledImg: https://cdn.17app.co/c313f980-1d7a-42cc-9843-b70cf42cf37d.png
    followIcon:
      activeImg:
      disabledImg:
    videoIcon:
      activeImg:
      disabledImg:
    feedIcon:
      activeImg: https://cdn.17app.co/78be5206-f9dc-4025-9d2b-071cebb2cead.png
      disabledImg: https://cdn.17app.co/fb8a3c89-835d-49e1-ae56-70b454540be7.png
    profileIcon:
      activeImg: https://cdn.17app.co/b63134ed-d29b-4e74-8511-8c7cf8468340.png
      disabledImg: https://cdn.17app.co/8c71f00c-d52b-46a6-a94e-b34193fb7e33.png
    navigationBarBackgroundImg:
    notificationsIconImg: https://cdn.17app.co/05a6d7f2-ed38-442b-be28-797e2e70741d.png
    leaderboardIconImg: https://cdn.17app.co/fb58a447-d5ce-4ad5-b6a5-e1cd396d00c2.png
#    navigationBarBackgroundImg: https://cdn.17app.co/cc49be76-6f59-48e4-a8cc-72b0eee16e4f.png
#    notificationsIconImg: https://cdn.17app.co/b2251e04-0568-463e-a6f1-ea9d466e4621.png
#    leaderboardIconImg: https://cdn.17app.co/4ad76eb2-e4be-44ac-8d0c-81b9aaee484b.png