iconInfos:
  - startTime: "2023-06-05 00:00:00 (GMT-0700)" #2023 Bestia II
    endTime: "2023-06-20 00:00:00 (GMT-0700)"
    liveIcon:
      activeImg: https://cdn.17app.co/1cc6d6d8-981e-48a9-aff3-6f6c652d1d6f.png
      disabledImg: https://cdn.17app.co/701028be-45ad-4001-9b83-af57adbec24b.png
    exploreIcon:
      activeImg: https://cdn.17app.co/c43f709f-0baa-4161-b10a-335d91aeab7d.png
      disabledImg: https://cdn.17app.co/bc507b1f-765c-4116-ab11-45bf8589cb4f.png
    feedIcon:
      activeImg: https://cdn.17app.co/a4148be5-3843-43ff-95e3-09757774b58f.png
      disabledImg: https://cdn.17app.co/37cc1d40-c474-4f44-8a4c-efef711506a1.png
    profileIcon:
      activeImg: https://cdn.17app.co/bd4eef9d-69ee-410a-b4da-35d1a91fff49.png
      disabledImg: https://cdn.17app.co/cae05ba5-55af-4411-aaba-3db421d2e9fa.png
    notificationsIconImg: https://cdn.17app.co/c31ba622-8dee-4e6f-b16a-698b6aa9233e.png
    leaderboardIconImg: https://cdn.17app.co/60b74637-9efc-476c-840a-7145848e3bfa.png