iconInfos:
  - startTime: "2023-03-28 00:00:00 (GMT-0700)" #2023 Easter
    endTime: "2023-04-15 00:00:00 (GMT-0700)"
    liveIcon:
      activeImg: https://cdn.17app.co/b773f8d9-52dc-4248-ba86-b9aa95b9bd0f.png
      disabledImg: https://cdn.17app.co/8b5fea59-6c1a-4ee0-948c-2d86fdbe4ee7.png
    exploreIcon:
      activeImg: https://cdn.17app.co/95db0edb-8de1-44c5-ae68-a5210cbcd0d0.png
      disabledImg: https://cdn.17app.co/c3346f47-4887-4bc5-87da-8f9cdff18671.png
    feedIcon:
      activeImg: https://cdn.17app.co/0937bc7c-4294-49a6-adb4-45cb2028c1bc.png
      disabledImg: https://cdn.17app.co/fad4db73-0d1c-466b-97d5-b30e1ab1c840.png
    profileIcon:
      activeImg: https://cdn.17app.co/9911822c-b6c3-4aea-b2a5-a9e005ec0639.png
      disabledImg: https://cdn.17app.co/ca74f090-e069-4cce-891a-4aba7d219de5.png
    notificationsIconImg: https://cdn.17app.co/48382a55-081d-48f3-87a6-d8fe103bf225.png
    leaderboardIconImg: https://cdn.17app.co/c97e3c3d-492e-405b-9fa4-41df90db8bee.png