watcher_channels:
  - "C0391PS2PE2" # shot_testing_ch

payment_maintain:
  general_notify: ""
  notify_rules: 
    - regex: "維護" 
      slack_ids: ""

third_party:
  notify_rules: 
    - regex: "Redis Scheduled Maintenance" 
      slack_ids: ""
    - regex: "Zendesk Maintenance"
      slack_ids: ""
