allowNegativePoint: true

regionSellingChannels:
  TW:
    - 19 # SellingChannelWebTwSuperVip
    - 58 # SellingChannelWebTwSuperVipNewebpay
    - 34 # SellingChannelWebTwBabyVipECPay
    - 57 # SellingChannelWebTwBabyVipNewebpay
    - 46 # SellingChannelWebTwBabyVipJkos
    - 47 # SellingChannelWebTwBabyVipMyCard
    - 48 # SellingChannelWebTwBabyVipGash
  JP:
    - 22 # SellingChannelWebJpSuperVipGMO
    - 53 # SellingChannelWebJpSuperVipPaidy
    - 21 # SellingChannelWebJpBabyVip
    - 52 # SellingChannelWebJpBabyVipPaidy
  HK:
    - 27 # SellingChannelWebHkVip
  US:
    - 24 # SellingChannelWebUsVip
  IN:
    - 80 # SellingChannelManualInVip
    - 69 # SellingChannelWebInSuperVipStripe
  DEFAULT:
    - 19 # SellingChannelWebTwSuperVip
    - 58 # SellingChannelWebTwSuperVipNewebpay
    - 34 # SellingChannelWebTwBabyVipECPay
    - 57 # SellingChannelWebTwBabyVipNewebpay
