goKart:
  version: 1.0.0
  goKartGiftTabs: [inGame]
  gifts:
    - itemId: hammer-1
      name: hammer
      tabName: inGame
    - itemId: shield-1
      name: shield
      tabName: inGame
    - itemId: missile-1
      name: missile
      tabName: inGame
    - itemId: heal-1
      name: heal
      tabName: inGame
    - itemId: star-1
      name: star
      tabName: inGame
    - itemId: angel-1
      name: angel
      tabName: inGame
