# birthdayCountdownDays: show incoming birthday icon in the range from birthday-n to birthday-1 day
# birthdayAfterDays: show after-birthday icon in the range from birthday+1 to birthday+n day
# enableACL: set to true to use ACL for authorization
# enableBQ: set to true to get follower information from BigQuery

birthdayCountdownDays: 3
birthdayAfterDays: 1
nearOutdatedDays:
  TW: 7
  JP: 60
enableACL: false
enableBQ: true
extendContractExcludeRegions: ["JP"]
renewContractIncludeRegions: ["JP"]
enableConcurrentGetStats: true
concurrentWorkerSize: 50
