# birthdayCountdownDays: show incoming birthday icon in the range from birthday-n to birthday-1 day
# birthdayAfterDays: show after-birthday icon in the range from birthday+1 to birthday+n day
# enableQueryACL: set to true to use ACL for authorization on queries
# enableMutationACL: set to true to use ACL for authorization on mutations
# enableBQ: set to true to get follower information from BigQuery

birthdayCountdownDays: 3
birthdayAfterDays: 1
nearOutdatedDays:
  TW: 7
  JP: 60
enableQueryACL: false
enableMutationACL: false
enableBQ: true
extendContractExcludeRegions: ["JP"]
renewContractIncludeRegions: ["JP"]
enableConcurrentGetStats: true
concurrentWorkerSize: 50
enableSlackContractNotif: true
maxTemplateSize: 25
