goKart:
  version: 1.0.0
  goKartGiftTabs: ["giftTab1", "giftTab2"]
  gifts:
    - id: '0'
      name: giftName1
      animation: Zoom
      directGiftAmount: Shield
      giftSequence: 0
      giftTabName: giftTab1
    - id: '1'
      name: giftName2
      animation: Zoom
      directGiftAmount: Angel
      giftSequence: 1
      giftTabName: giftTab1
    - id: '2'
      name: giftName3
      animation: Zoom
      directGiftAmount: Shield
      giftSequence: 2
      giftTabName: giftTab2