goKart:
  version: 1.0.1
  goKartGiftTabs: [inGame]
  gifts:
    - itemId: hammer-1
      name: hammer
      tabName: inGame
      point: 300
    - itemId: shield-1
      name: shield
      tabName: inGame
      point: 500
    - itemId: missile-1
      name: missile
      tabName: inGame
      point: 800
    - itemId: heal-1
      name: heal
      tabName: inGame
      point: 99
    - itemId: star-1
      name: star
      tabName: inGame
      point: 39
    - itemId: angel-1
      name: angel
      tabName: inGame
      point: 2000
