goKart:
  version: 1.0.0
  goKartGiftTabs: ["inGame"]
  gifts:
    - itemId: hammer-1
      name: hammer
      tabName: inGame
    - id: shield-1
      name: shield
      tabName: inGame
    - id: missile-1
      name: missile
      tabName: inGame
    - id: heal-1
      name: heal
      tabName: inGame
    - id: star-1
      name: star
      tabName: inGame
    - id: angel-1
      name: angel
      tabName: inGame
