platform:
  ios:
    default:
      enable: false
      features:
        - id: skinPinking
          enable: true
          min: 0
          max: 1
          default: 0.2
          adjustMode: slider
          displayName: 粉
          iconUrl: http://cdn.17app.co/producer-badge-skot-38x38px.png
          type: 360
        - id: skinRedden
          enable: true
          min: 0
          max: 1
          default: 0.4
          adjustMode: slider
          displayName: 12345
          iconUrl: http://cdn.17app.co/producer-badge-razor-38x38px.png
          type: 360
        - id: skinWhitening
          enable: true
          min: 0
          max: 1
          default: 0.6
          adjustMode: slider
          displayName: 白
          iconUrl: http://cdn.17app.co/producer-badge-tower-38x38px.png
          type: 360
        - id: skinSoften
          enable: true
          min: 5
          max: 95
          default: 45
          adjustMode: slider
          displayName: 軟
          iconUrl: http://cdn.17app.co/producer-badge-alex-38x38px.png
          type: 360
        - id: 17skin
          enable: true
          min: 0
          max: 1
          default: 0
          adjustMode: toggle
          displayName: 美肌
          iconUrl: http://cdn.17app.co/producer-badge-jerryc-38x38px.png
        - id: bigEye
          enable: true
          min: 0
          max: 100
          default: 50
          adjustMode: slider
          displayName: 大眼
          iconUrl: http://cdn.17app.co/producer-badge-starrchen-38x38px.png
          type: 360
        - id: thinFace
          enable: true
          min: 1
          max: 99
          default: 49
          adjustMode: slider
          displayName: 瘦臉
          iconUrl: http://cdn.17app.co/producer-badge-roger-38x38px.png
          type: 360
    iPhone5,3:
  android:
    default:
      enable: false
      features:
        - id: skinPinking
          enable: true
          min: 0
          max: 1
          default: 0.2
          adjustMode: slider
          displayName: 粉
          iconUrl: http://cdn.17app.co/producer-badge-skot-38x38px.png
          type: 360
        - id: skinRedden
          enable: true
          min: 0
          max: 1
          default: 0.4
          adjustMode: slider
          displayName: 12345
          iconUrl: http://cdn.17app.co/producer-badge-razor-38x38px.png
          type: 360
        - id: skinWhitening
          enable: true
          min: 0
          max: 1
          default: 0.6
          adjustMode: slider
          displayName: 白
          iconUrl: http://cdn.17app.co/producer-badge-tower-38x38px.png
          type: 360
        - id: skinSoften
          enable: true
          min: 5
          max: 95
          default: 45
          adjustMode: slider
          displayName: 軟
          iconUrl: http://cdn.17app.co/producer-badge-alex-38x38px.png
          type: 360
        - id: 17skin
          enable: true
          min: 0
          max: 1
          default: 0
          adjustMode: toggle
          displayName: 美肌
          iconUrl: http://cdn.17app.co/producer-badge-jerryc-38x38px.png
        - id: bigEye
          enable: true
          min: 0
          max: 100
          default: 50
          adjustMode: slider
          displayName: 大眼
          iconUrl: http://cdn.17app.co/producer-badge-starrchen-38x38px.png
          type: 360
        - id: thinFace
          enable: true
          min: 1
          max: 99
          default: 49
          adjustMode: slider
          displayName: 瘦臉
          iconUrl: http://cdn.17app.co/producer-badge-roger-38x38px.png
          type: 360
    Pixel 2:
