platform:
  ios:
    default:
      - name: 17
        enable: true
      - name: 360
        enable: false
        features:
          - id: bigEye
            enable: true
            min: 0
            max: 50
            default: 0
          - id: thinFace
            enable: true
            min: 0
            max: 50
            default: 0
          - id: skinPinking
            enable: true
            min: 0
            max: 100
            default: 50
          - id: skinRedden
            enable: true
            min: 0
            max: 100
            default: 50
          - id: skinWhitening
            enable: true
            min: 0
            max: 100
            default: 50
          - id: skinSoften
            enable: true
            min: 0
            max: 100
            default: 50
    iPhone1,3:
    iPhone2,3:
    iPhone3,3:
    iPhone4,3:
  android:
    default:
      - name: 17
        enable: true
      - name: 360
        enable: false
        features:
          - id: bigEye
            enable: true
            min: 0
            max: 50
            default: 0
          - id: thinFace
            enable: true
            min: 0
            max: 50
            default: 0
          - id: skinPinking
            enable: true
            min: 0
            max: 100
            default: 50
          - id: skinRedden
            enable: true
            min: 0
            max: 100
            default: 50
          - id: skinWhitening
            enable: true
            min: 0
            max: 100
            default: 50
          - id: skinSoften
            enable: true
            min: 0
            max: 100
            default: 50