endpoint: "http://34.149.133.92"
token: <SECRET_TAG>CiQAmBGjTU4kknhKSdA0veleoSSUmQe+cNl0rRf88bl2H9MRVt8STQClekYIsXaD7TBQ6meQ7p6CjTdDZt9xv8HskrH3Mg4ErAlIsaQQW92ueXPYM9hPhRvmV7loAiLOdJr78IhQ+0orZ48YgX2Saz4djlgw</SECRET_TAG>
